/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type SchemaVersion = "0.1";
export type RunId = string;
export type Tools = Tool[] | null;
export type Name = string;
export type Description = string | null;
export type Title = string | null;
export type Outputschema = {
  [k: string]: unknown;
} | null;
export type Meta = {
  [k: string]: unknown;
} | null;
export type McpServers = McpServer[] | null;
export type Id = string;
export type Transport = "http" | "stdio";
export type Url = string | null;
export type Type = "bearer";
export type TokenEnv = string;
export type Command = string[] | null;
export type Args = string[] | null;
export type Env = {
  [k: string]: string;
} | null;
export type InitTimeoutMs = number;
export type Meta1 = {
  [k: string]: unknown;
} | null;
export type AllowedTools = string[] | null;
export type Verifiers = Verifier[] | null;
export type Name1 = string;
export type Trigger = string;
export type Source = VerifierSourceShell | VerifierSourceApproval;
export type Shell = string;
export type Prompt = string | null;
export type OnFailure = "halt" | "inject_correction" | "continue";
export type OnFailure1 = "halt" | "inject_correction" | "continue";
export type CorrectionMessage = string | null;
export type TimeoutMs = number;
export type MaxCostUsd = number | null;
export type MaxSteps = number | null;
export type MaxTokens = number | null;
export type MaxDurationSeconds = number | null;
export type OutputSchema = {
  [k: string]: unknown;
} | null;
export type Subagents = Subagent[] | null;
export type Name2 = string;
export type Description1 = string;
export type Inputschema1 = {
  [k: string]: unknown;
} | null;
export type SystemPrompt = string | null;
export type Model = string | null;
export type InheritTools = boolean;
export type AllowedTools1 = string[] | null;
export type Tools1 = Tool[] | null;
export type McpServers1 = McpServer[] | null;
export type Skills = Skill[] | null;
export type Name3 = string;
export type AepSource = string;
export type AepConfig = {
  [k: string]: unknown;
} | null;
export type Verifiers1 = Verifier[] | null;
export type OutputSchema1 = {
  [k: string]: unknown;
} | null;
export type Subagents1 = Subagent[] | null;
export type Prompt1 = string | null;
export type SystemPrompt1 = string | null;
export type Model1 = string | null;
export type Skills1 = Skill[] | null;
export type ThreadId = string | null;
export type Tags = string[] | null;
export type Meta2 = {
  [k: string]: unknown;
} | null;
/**
 * This interface was referenced by `AEPV01Config`'s JSON-Schema
 * via the `definition` "OnFailure".
 */
export type OnFailure2 = "halt" | "inject_correction" | "continue";

/**
 * Supervisor → runner setup message. Declares the agent's complete environment (boundary, tools, mcp_servers, skills, verifiers, prompts). Sent once at startup. The supervisor MUST NOT modify the environment mid-run.
 */
export interface AEPV01Config {
  schema_version: SchemaVersion;
  run_id: RunId;
  tools?: Tools;
  mcp_servers?: McpServers;
  allowed_tools?: AllowedTools;
  verifiers?: Verifiers;
  boundary?: Boundary | null;
  output_schema?: OutputSchema;
  subagents?: Subagents;
  prompt?: Prompt1;
  system_prompt?: SystemPrompt1;
  model?: Model1;
  skills?: Skills1;
  thread_id?: ThreadId;
  tags?: Tags;
  meta?: Meta2;
}
/**
 * MCP-shaped tool descriptor. Per the MCP 2025-11-25 spec.
 *
 * `inputSchema` and `outputSchema` are camelCase per MCP. The optional
 * `_meta.aep.timeout_ms` is AEP's extension (MCP defines `_meta` as the
 * extension slot).
 *
 * This interface was referenced by `AEPV01Config`'s JSON-Schema
 * via the `definition` "Tool".
 */
export interface Tool {
  name: Name;
  description?: Description;
  title?: Title;
  inputSchema: Inputschema;
  outputSchema?: Outputschema;
  _meta?: Meta;
}
export interface Inputschema {
  [k: string]: unknown;
}
/**
 * External MCP server endpoint. The runner connects, runs initialize +
 * tools/list, and merges returned tools into the effective surface.
 *
 * This interface was referenced by `AEPV01Config`'s JSON-Schema
 * via the `definition` "McpServer".
 */
export interface McpServer {
  id: Id;
  transport: Transport;
  url?: Url;
  auth?: McpHttpAuth | null;
  command?: Command;
  args?: Args;
  env?: Env;
  init_timeout_ms?: InitTimeoutMs;
  _meta?: Meta1;
}
/**
 * Auth for an MCP server reachable via HTTP.
 *
 * This interface was referenced by `AEPV01Config`'s JSON-Schema
 * via the `definition` "McpHttpAuth".
 */
export interface McpHttpAuth {
  type?: Type;
  token_env: TokenEnv;
}
/**
 * Declarative check at a trigger point. AEP-specific (no upstream).
 *
 * Two reaction polarities:
 *   - `on_failure` (default `continue`): action when the check FAILS.
 *     The common case — invariants that fail trigger correction or halt.
 *   - `on_success` (default `continue`): action when the check PASSES.
 *     Use `on_success: halt` for declarative convergence — "stop when
 *     this condition is met". Halt-on-success terminates with
 *     `reason=converged`; halt-on-failure terminates with
 *     `reason=verifier_failed`.
 *
 * Sources:
 *   - `{shell: "..."}` — deterministic subprocess; exit 0 = pass.
 *   - `{approval: {prompt?: "..."}}` — pings the supervisor for a
 *     human or policy decision via the `approval_requested` /
 *     `approval_resolved` RPC pair. Approved = pass; denied or timed
 *     out = fail. Use with `pre_tool:<name>` triggers for human-in-
 *     the-loop gates on destructive actions.
 *
 * A check can set both: e.g. `on_success: halt` + `on_failure: continue`
 * means "halt when this passes, otherwise keep going". Setting both to
 * `halt` is allowed but unusual (halts no matter what — useful for
 * forced checkpoints).
 *
 * This interface was referenced by `AEPV01Config`'s JSON-Schema
 * via the `definition` "Verifier".
 */
export interface Verifier {
  name: Name1;
  trigger: Trigger;
  source: Source;
  on_failure?: OnFailure;
  on_success?: OnFailure1;
  correction_message?: CorrectionMessage;
  timeout_ms?: TimeoutMs;
}
/**
 * Shell-source verifier: pass/fail comes from the exit code of a
 * subprocess. Deterministic; runs in-process on the runner's host.
 *
 * This interface was referenced by `AEPV01Config`'s JSON-Schema
 * via the `definition` "VerifierSourceShell".
 */
export interface VerifierSourceShell {
  shell: Shell;
}
/**
 * Approval-source verifier: pass/fail comes from the supervisor's
 * response to an `aep.approval_requested` RPC. Used at gate triggers
 * (typically `pre_tool:<name>`) where a human or policy decides
 * whether the agent proceeds. Approved → pass; denied or timed-out →
 * fail. Distinct from shell sources because the decision is non-
 * deterministic and originates outside the runner.
 *
 * This interface was referenced by `AEPV01Config`'s JSON-Schema
 * via the `definition` "VerifierSourceApproval".
 */
export interface VerifierSourceApproval {
  approval: _ApprovalSpec;
}
/**
 * The body of `{approval: {...}}` — the prompt and any future
 * knobs that describe what the supervisor is being asked to approve.
 *
 * This interface was referenced by `AEPV01Config`'s JSON-Schema
 * via the `definition` "_ApprovalSpec".
 */
export interface _ApprovalSpec {
  prompt?: Prompt;
}
/**
 * Hard limits the agent enforces. Strict-greater per SPEC §9.2.
 *
 * Cost / tokens / duration are CONSUMPTION boundaries — checked after
 * each turn and tool, and may overshoot a max by one final event because
 * the cost/token spend of the next call can't be projected pre-call.
 * Step is a PROJECTION boundary — checked before starting the next turn,
 * so `max_steps: N` runs EXACTLY N turns.
 *
 * This interface was referenced by `AEPV01Config`'s JSON-Schema
 * via the `definition` "Boundary".
 */
export interface Boundary {
  max_cost_usd?: MaxCostUsd;
  max_steps?: MaxSteps;
  max_tokens?: MaxTokens;
  max_duration_seconds?: MaxDurationSeconds;
}
/**
 * Declares a sub-agent the parent can delegate to.
 *
 * Sits alongside `tools` and `skills` as a top-level Config primitive: the
 * supervisor declares the full set of subagents up front, the parent agent
 * invokes one by name at runtime. The model surface is MCP-shaped (`name`,
 * `description`, `inputSchema`) so the model sees a subagent the same way
 * it sees a tool. The wire surface is its own lifecycle —
 * `subagent_invoked` / `subagent_returned` / `subagent_failed` — so
 * nested turns and tool calls observe as their own span tree rather than
 * flatten into a single tool call.
 *
 * A Subagent carries an environment slice that mirrors Config (its own
 * `system_prompt`, `model`, `tools`, `skills`, `verifiers`, `boundary`,
 * `output_schema`). The subagent runs in a fresh conversation —
 * `inherit_tools=False` by default (matches Google ADK; safer than the
 * Claude Agent SDK default of inheriting). Skills and prompt context are
 * never inherited.
 *
 * This interface was referenced by `AEPV01Config`'s JSON-Schema
 * via the `definition` "Subagent".
 */
export interface Subagent {
  name: Name2;
  description: Description1;
  inputSchema?: Inputschema1;
  system_prompt?: SystemPrompt;
  model?: Model;
  inherit_tools?: InheritTools;
  allowed_tools?: AllowedTools1;
  tools?: Tools1;
  mcp_servers?: McpServers1;
  skills?: Skills;
  verifiers?: Verifiers1;
  boundary?: Boundary | null;
  output_schema?: OutputSchema1;
  subagents?: Subagents1;
}
/**
 * Reference to a SKILL.md following the agentskills.io specification.
 *
 * `name` MUST follow agentskills.io rules (1-64 chars, lowercase a-z digits
 * hyphens, no leading/trailing hyphen, no consecutive hyphens). The
 * `aep_source` and `aep_config` fields are AEP extensions; agentskills.io
 * doesn't define a remote-load scheme.
 *
 * This interface was referenced by `AEPV01Config`'s JSON-Schema
 * via the `definition` "Skill".
 */
export interface Skill {
  name: Name3;
  "aep.source": AepSource;
  "aep.config"?: AepConfig;
}
