/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Runner → supervisor event. Each event is a CloudEvent 1.0 envelope carrying a typed `data` payload. The `type` field is the discriminator (reverse-DNS, `aep.*` namespace). Attribute names inside `data` follow OpenTelemetry GenAI semantic conventions and OTel span identification (`trace_id`, `span_id`, `parent_span_id`); AEP-specific attributes are namespaced `aep.*`.
 */
export type AEPV01Event =
  | AgentStartedEvent
  | AgentStoppedEvent
  | ModelTurnStartedEvent
  | ModelTurnEndedEvent
  | ToolInvokedEvent
  | ToolReturnedEvent
  | ToolFailedEvent
  | SubagentInvokedEvent
  | SubagentReturnedEvent
  | SubagentFailedEvent
  | TextEmittedEvent
  | ReasoningEmittedEvent
  | RefusalRecordedEvent
  | CostRecordedEvent
  | SkillLoadedEvent
  | SkillExecutedEvent
  | ErrorOccurredEvent
  | ToolExecRequestEvent
  | ToolExecResolvedEvent
  | ToolExecTimedOutEvent
  | ApprovalRequestedEvent
  | ApprovalResolvedEvent
  | VerifierEvaluatedEvent
  | McpServerConnectedEvent
  | McpServerDisconnectedEvent;
export type Specversion = "1.0";
export type Id = string;
export type Time = string;
export type Subject = string | null;
export type Datacontenttype = string | null;
export type Dataschema = string | null;
export type AepCorrelationId = string | null;
export type Type = "aep.agent_started";
export type Source = "aep://runner";
export type TraceId = string;
export type SpanId = string;
export type ParentSpanId = string;
export type GenAiProviderName = string | null;
export type GenAiOperationName = ("invoke_agent" | "chat") | null;
export type GenAiRequestModel = string | null;
export type Prompt = string | null;
export type SystemPrompt = string | null;
export type Tools = _ToolDecl[] | null;
export type Name = string;
export type Description = string | null;
export type Inputschema = {
  [k: string]: unknown;
} | null;
export type AepDispatchTarget = ("supervisor_rpc" | "mcp_server" | "local") | null;
export type AepMcpServerId = string | null;
export type Skills = string[] | null;
export type Subagents = _SubagentDecl[] | null;
export type Name1 = string;
export type Description1 = string | null;
export type Inputschema1 = {
  [k: string]: unknown;
} | null;
export type AepThreadId = string | null;
export type AepSessionId = string | null;
export type AepTags = string[] | null;
export type AepMeta = {
  [k: string]: unknown;
} | null;
export type AepSchemaVersion = "0.1";
export type Specversion1 = "1.0";
export type Id1 = string;
export type Time1 = string;
export type Subject1 = string | null;
export type Datacontenttype1 = string | null;
export type Dataschema1 = string | null;
export type AepCorrelationId1 = string | null;
export type Type1 = "aep.agent_stopped";
export type Source1 = "aep://runner";
export type TraceId1 = string;
export type SpanId1 = string;
export type ParentSpanId1 = string;
export type StopReason =
  | "converged"
  | "budget_exhausted"
  | "token_limit"
  | "turn_limit"
  | "duration_limit"
  | "error"
  | "interrupted"
  | "verifier_failed"
  | "refused";
export type TotalCostUsd = number;
export type TotalTokens = number;
export type TotalTurns = number;
export type TokensInputTotal = number | null;
export type TokensOutputTotal = number | null;
export type TokensCacheReadTotal = number | null;
export type TokensCacheWriteTotal = number | null;
export type ToolsInvoked = {
  [k: string]: number;
} | null;
export type StartedAt = string | null;
export type DurationMs = number | null;
export type AepTotalTokens = number | null;
export type AepTotalCostUsd = number | null;
export type AepTotalTurns = number | null;
export type AepDurationMs = number | null;
export type Specversion2 = "1.0";
export type Id2 = string;
export type Time2 = string;
export type Subject2 = string | null;
export type Datacontenttype2 = string | null;
export type Dataschema2 = string | null;
export type AepCorrelationId2 = string | null;
export type Type2 = "aep.model_turn_started";
export type Source2 = "aep://runner";
export type TraceId2 = string;
export type SpanId2 = string;
export type ParentSpanId2 = string;
export type Step = number;
export type AepContextMessages = number | null;
export type GenAiRequestStream = boolean | null;
export type Specversion3 = "1.0";
export type Id3 = string;
export type Time3 = string;
export type Subject3 = string | null;
export type Datacontenttype3 = string | null;
export type Dataschema3 = string | null;
export type AepCorrelationId3 = string | null;
export type Type3 = "aep.model_turn_ended";
export type Source3 = "aep://runner";
export type TraceId3 = string;
export type SpanId3 = string;
export type ParentSpanId3 = string;
export type Step1 = number;
export type DurationMs1 = number;
export type GenAiProviderName1 = string | null;
export type GenAiRequestModel1 = string | null;
export type GenAiResponseModel = string | null;
export type GenAiResponseFinishReasons = string[] | null;
export type GenAiResponseTimeToFirstChunk = number | null;
export type GenAiUsageInputTokens = number;
export type GenAiUsageOutputTokens = number;
export type GenAiUsageCacheReadInputTokens = number | null;
export type GenAiUsageCacheCreationInputTokens = number | null;
export type GenAiUsageReasoningOutputTokens = number | null;
export type AepCostUsd = number;
export type AepCostSource = ("computed" | "reported" | "unknown") | null;
export type Specversion4 = "1.0";
export type Id4 = string;
export type Time4 = string;
export type Subject4 = string | null;
export type Datacontenttype4 = string | null;
export type Dataschema4 = string | null;
export type AepCorrelationId4 = string | null;
export type Type4 = "aep.tool_invoked";
export type Source4 = "aep://runner";
export type TraceId4 = string;
export type SpanId4 = string;
export type ParentSpanId4 = string;
export type Step2 = number;
export type GenAiToolCallId = string;
export type GenAiToolName = string;
export type AepToolDispatchTarget = ("supervisor_rpc" | "mcp_server" | "local") | null;
export type AepToolSubtype = string | null;
export type Specversion5 = "1.0";
export type Id5 = string;
export type Time5 = string;
export type Subject5 = string | null;
export type Datacontenttype5 = string | null;
export type Dataschema5 = string | null;
export type AepCorrelationId5 = string | null;
export type Type5 = "aep.tool_returned";
export type Source5 = "aep://runner";
export type TraceId5 = string;
export type SpanId5 = string;
export type ParentSpanId5 = string;
export type Step3 = number;
export type GenAiToolCallId1 = string;
export type GenAiToolName1 = string;
export type DurationMs2 = number;
export type AepToolResultText = string;
export type AepToolRejected = boolean | null;
export type AepToolRejectionReason = string | null;
export type Specversion6 = "1.0";
export type Id6 = string;
export type Time6 = string;
export type Subject6 = string | null;
export type Datacontenttype6 = string | null;
export type Dataschema6 = string | null;
export type AepCorrelationId6 = string | null;
export type Type6 = "aep.tool_failed";
export type Source6 = "aep://runner";
export type TraceId6 = string;
export type SpanId6 = string;
export type ParentSpanId6 = string;
export type Step4 = number;
export type GenAiToolCallId2 = string;
export type GenAiToolName2 = string;
export type AepToolError = string;
export type AepToolErrorCode = number | null;
export type Specversion7 = "1.0";
export type Id7 = string;
export type Time7 = string;
export type Subject7 = string | null;
export type Datacontenttype7 = string | null;
export type Dataschema7 = string | null;
export type AepCorrelationId7 = string | null;
export type Type7 = "aep.subagent_invoked";
export type Source7 = "aep://runner";
export type TraceId7 = string;
export type SpanId7 = string;
export type ParentSpanId7 = string;
export type Step5 = number;
export type GenAiAgentName = string;
export type GenAiAgentDescription = string | null;
export type GenAiOperationName1 = "invoke_agent";
export type AepSubagentInvocationId = string;
export type Specversion8 = "1.0";
export type Id8 = string;
export type Time8 = string;
export type Subject8 = string | null;
export type Datacontenttype8 = string | null;
export type Dataschema8 = string | null;
export type AepCorrelationId8 = string | null;
export type Type8 = "aep.subagent_returned";
export type Source8 = "aep://runner";
export type TraceId8 = string;
export type SpanId8 = string;
export type ParentSpanId8 = string;
export type Step6 = number;
export type GenAiAgentName1 = string;
export type AepSubagentInvocationId1 = string;
export type DurationMs3 = number;
export type AepSubagentResultText = string;
export type Specversion9 = "1.0";
export type Id9 = string;
export type Time9 = string;
export type Subject9 = string | null;
export type Datacontenttype9 = string | null;
export type Dataschema9 = string | null;
export type AepCorrelationId9 = string | null;
export type Type9 = "aep.subagent_failed";
export type Source9 = "aep://runner";
export type TraceId9 = string;
export type SpanId9 = string;
export type ParentSpanId9 = string;
export type Step7 = number;
export type GenAiAgentName2 = string;
export type AepSubagentInvocationId2 = string;
export type DurationMs4 = number;
export type AepSubagentError = string;
export type AepSubagentErrorCode = string | null;
export type Specversion10 = "1.0";
export type Id10 = string;
export type Time10 = string;
export type Subject10 = string | null;
export type Datacontenttype10 = string | null;
export type Dataschema10 = string | null;
export type AepCorrelationId10 = string | null;
export type Type10 = "aep.text_emitted";
export type Source10 = "aep://runner";
export type TraceId10 = string;
export type SpanId10 = string;
export type ParentSpanId10 = string;
export type Step8 = number;
export type AepText = string;
export type Specversion11 = "1.0";
export type Id11 = string;
export type Time11 = string;
export type Subject11 = string | null;
export type Datacontenttype11 = string | null;
export type Dataschema11 = string | null;
export type AepCorrelationId11 = string | null;
export type Type11 = "aep.reasoning_emitted";
export type Source11 = "aep://runner";
export type TraceId11 = string;
export type SpanId11 = string;
export type ParentSpanId11 = string;
export type Step9 = number;
export type AepReasoningText = string;
export type AepReasoningSignature = string | null;
export type AepReasoningRedacted = boolean | null;
export type Specversion12 = "1.0";
export type Id12 = string;
export type Time12 = string;
export type Subject12 = string | null;
export type Datacontenttype12 = string | null;
export type Dataschema12 = string | null;
export type AepCorrelationId12 = string | null;
export type Type12 = "aep.refusal_recorded";
export type Source12 = "aep://runner";
export type TraceId12 = string;
export type SpanId12 = string;
export type ParentSpanId12 = string;
export type Step10 = number;
export type AepRefusalReason = string;
export type AepRefusalMessage = string | null;
export type AepRefusalCategory = string | null;
export type AepRefusalProvider = string | null;
export type Specversion13 = "1.0";
export type Id13 = string;
export type Time13 = string;
export type Subject13 = string | null;
export type Datacontenttype13 = string | null;
export type Dataschema13 = string | null;
export type AepCorrelationId13 = string | null;
export type Type13 = "aep.cost_recorded";
export type Source13 = "aep://runner";
export type TraceId13 = string;
export type SpanId13 = string;
export type ParentSpanId13 = string;
export type AepCostSource1 = ("computed" | "reported" | "unknown") | null;
export type Specversion14 = "1.0";
export type Id14 = string;
export type Time14 = string;
export type Subject14 = string | null;
export type Datacontenttype14 = string | null;
export type Dataschema14 = string | null;
export type AepCorrelationId14 = string | null;
export type Type14 = "aep.skill_loaded";
export type Source14 = "aep://runner";
export type TraceId14 = string;
export type SpanId14 = string;
export type ParentSpanId14 = string;
export type Step11 = number;
export type AepSkillName = string;
export type AepSkillSource = string | null;
export type Specversion15 = "1.0";
export type Id15 = string;
export type Time15 = string;
export type Subject15 = string | null;
export type Datacontenttype15 = string | null;
export type Dataschema15 = string | null;
export type AepCorrelationId15 = string | null;
export type Type15 = "aep.skill_executed";
export type Source15 = "aep://runner";
export type TraceId15 = string;
export type SpanId15 = string;
export type ParentSpanId15 = string;
export type Step12 = number;
export type AepSkillName1 = string;
export type Specversion16 = "1.0";
export type Id16 = string;
export type Time16 = string;
export type Subject16 = string | null;
export type Datacontenttype16 = string | null;
export type Dataschema16 = string | null;
export type AepCorrelationId16 = string | null;
export type Type16 = "aep.error_occurred";
export type Source16 = "aep://runner";
export type TraceId16 = string;
export type SpanId16 = string;
export type ParentSpanId16 = string;
export type ErrorCode = "rate_limit" | "context_limit" | "auth_error" | "runner_crash" | "accounting_reset" | "unknown";
export type AepErrorMessage = string;
export type Specversion17 = "1.0";
export type Id17 = string;
export type Time17 = string;
export type Subject17 = string | null;
export type Datacontenttype17 = string | null;
export type Dataschema17 = string | null;
export type AepCorrelationId17 = string | null;
export type Type17 = "aep.tool_exec_request";
export type Source17 = "aep://runner";
export type TraceId17 = string;
export type SpanId17 = string;
export type ParentSpanId17 = string;
export type Step13 = number;
export type AepRequestId = string;
export type GenAiToolCallId3 = string;
export type AepTimeoutMs = number;
export type AepToolDispatchTarget1 = "supervisor_rpc" | "mcp_server";
export type AepMcpServerId1 = string | null;
export type GenAiToolName3 = string;
export type Jsonrpc = "2.0";
export type Id18 = string | number;
export type Method = string;
export type Specversion18 = "1.0";
export type Id19 = string;
export type Time18 = string;
export type Subject18 = string | null;
export type Datacontenttype18 = string | null;
export type Dataschema18 = string | null;
export type AepCorrelationId18 = string | null;
export type Type18 = "aep.tool_exec_resolved";
export type Source18 = string;
export type TraceId18 = string;
export type SpanId18 = string;
export type ParentSpanId18 = string;
export type AepRequestId1 = string;
export type GenAiToolName4 = string | null;
export type Jsonrpc1 = "2.0";
export type Id20 = string | number | null;
export type Code = number;
export type Message = string;
export type Specversion19 = "1.0";
export type Id21 = string;
export type Time19 = string;
export type Subject19 = string | null;
export type Datacontenttype19 = string | null;
export type Dataschema19 = string | null;
export type AepCorrelationId19 = string | null;
export type Type19 = "aep.tool_exec_timed_out";
export type Source19 = "aep://runner";
export type TraceId19 = string;
export type SpanId19 = string;
export type ParentSpanId19 = string;
export type Step14 = number;
export type AepRequestId2 = string;
export type GenAiToolCallId4 = string;
export type GenAiToolName5 = string;
export type AepTimeoutMs1 = number;
export type Specversion20 = "1.0";
export type Id22 = string;
export type Time20 = string;
export type Subject20 = string | null;
export type Datacontenttype20 = string | null;
export type Dataschema20 = string | null;
export type AepCorrelationId20 = string | null;
export type Type20 = "aep.approval_requested";
export type Source20 = "aep://runner";
export type TraceId20 = string;
export type SpanId20 = string;
export type ParentSpanId20 = string;
export type Step15 = number;
export type AepApprovalId = string;
export type AepTimeoutMs2 = number;
export type AepVerifierName = string;
export type AepApprovalPrompt = string | null;
export type GenAiToolName6 = string | null;
export type GenAiToolCallId5 = string | null;
export type GenAiToolCallArguments1 = {
  [k: string]: unknown;
} | null;
export type Specversion21 = "1.0";
export type Id23 = string;
export type Time21 = string;
export type Subject21 = string | null;
export type Datacontenttype21 = string | null;
export type Dataschema21 = string | null;
export type AepCorrelationId21 = string | null;
export type Type21 = "aep.approval_resolved";
export type Source21 = string;
export type TraceId21 = string;
export type SpanId21 = string;
export type ParentSpanId21 = string;
export type AepApprovalId1 = string;
export type AepApprovalApproved = boolean;
export type AepApprovalReason = string | null;
export type Specversion22 = "1.0";
export type Id24 = string;
export type Time22 = string;
export type Subject22 = string | null;
export type Datacontenttype22 = string | null;
export type Dataschema22 = string | null;
export type AepCorrelationId22 = string | null;
export type Type22 = "aep.verifier_evaluated";
export type Source22 = "aep://runner";
export type TraceId22 = string;
export type SpanId22 = string;
export type ParentSpanId22 = string;
export type AepVerifierName1 = string;
export type AepVerifierPassed = boolean;
export type AepVerifierDurationMs = number;
export type Step16 = number | null;
/**
 * Why a verifier failed for non-logic reasons. Distinguishes
 * 'environment broken' (script missing, timed out, crashed) from
 * 'rule legitimately failed' (passed=false with no error).
 */
export type VerifierError = "source_unavailable" | "source_timed_out" | "source_crashed";
export type AepVerifierSubjectCallIds = string[] | null;
export type AepVerifierSubjectRequestIds = string[] | null;
export type AepVerifierData = {
  [k: string]: unknown;
} | null;
export type Specversion23 = "1.0";
export type Id25 = string;
export type Time23 = string;
export type Subject23 = string | null;
export type Datacontenttype23 = string | null;
export type Dataschema23 = string | null;
export type AepCorrelationId23 = string | null;
export type Type23 = "aep.mcp_server_connected";
export type Source23 = "aep://runner";
export type TraceId23 = string;
export type SpanId23 = string;
export type ParentSpanId23 = string;
export type AepMcpServerId2 = string;
export type AepMcpProtocolVersion = string;
export type AepMcpToolCount = number;
export type AepMcpServerName = string | null;
export type AepMcpServerVersion = string | null;
export type AepMcpTools = _ToolDecl[] | null;
export type AepMcpStatus = ("connected" | "failed" | "needs-auth" | "pending" | "disabled") | null;
export type AepMcpError = string | null;
export type Specversion24 = "1.0";
export type Id26 = string;
export type Time24 = string;
export type Subject24 = string | null;
export type Datacontenttype24 = string | null;
export type Dataschema24 = string | null;
export type AepCorrelationId24 = string | null;
export type Type24 = "aep.mcp_server_disconnected";
export type Source24 = "aep://runner";
export type TraceId24 = string;
export type SpanId24 = string;
export type ParentSpanId24 = string;
export type AepMcpServerId3 = string;
export type AepMcpDisconnectReason = "clean" | "error";
export type AepMcpDisconnectMessage = string | null;

export interface AgentStartedEvent {
  specversion?: Specversion;
  id?: Id;
  time?: Time;
  subject?: Subject;
  datacontenttype?: Datacontenttype;
  dataschema?: Dataschema;
  "aep.correlation_id"?: AepCorrelationId;
  type?: Type;
  source?: Source;
  data: AgentStartedData;
}
/**
 * Payload of aep.agent_started events.
 */
export interface AgentStartedData {
  trace_id: TraceId;
  span_id: SpanId;
  parent_span_id: ParentSpanId;
  "gen_ai.provider.name"?: GenAiProviderName;
  "gen_ai.operation.name"?: GenAiOperationName;
  "gen_ai.request.model"?: GenAiRequestModel;
  prompt?: Prompt;
  system_prompt?: SystemPrompt;
  tools?: Tools;
  skills?: Skills;
  subagents?: Subagents;
  "aep.thread_id"?: AepThreadId;
  "aep.session_id"?: AepSessionId;
  "aep.tags"?: AepTags;
  "aep.meta"?: AepMeta;
  "aep.schema_version"?: AepSchemaVersion;
  [k: string]: unknown;
}
/**
 * Tool descriptor in `agent_started.data.tools` — MCP-shaped + AEP fields.
 */
export interface _ToolDecl {
  name: Name;
  description?: Description;
  inputSchema?: Inputschema;
  "aep.dispatch_target"?: AepDispatchTarget;
  "aep.mcp_server_id"?: AepMcpServerId;
  [k: string]: unknown;
}
/**
 * Subagent descriptor in `agent_started.data.subagents` — what the
 * parent model sees when deciding whether to delegate. Same MCP-shaped
 * triple (`name`, `description`, `inputSchema`) tools use, so adapters
 * can render subagents to the model's tool list with no translation.
 *
 * `description` is optional to match `_ToolDecl`: when surfacing a
 * runner-built-in subagent (e.g. the Claude Agent SDK's `general-purpose`)
 * the runner has authoritative knowledge of the name but not the prose
 * description. Honest-null beats authored-prose-that-drifts.
 */
export interface _SubagentDecl {
  name: Name1;
  description?: Description1;
  inputSchema?: Inputschema1;
  [k: string]: unknown;
}
export interface AgentStoppedEvent {
  specversion?: Specversion1;
  id?: Id1;
  time?: Time1;
  subject?: Subject1;
  datacontenttype?: Datacontenttype1;
  dataschema?: Dataschema1;
  "aep.correlation_id"?: AepCorrelationId1;
  type?: Type1;
  source?: Source1;
  data: AgentStoppedData;
}
export interface AgentStoppedData {
  trace_id: TraceId1;
  span_id: SpanId1;
  parent_span_id: ParentSpanId1;
  "aep.reason": StopReason;
  "aep.state": RunStateSnapshot;
  "aep.total_tokens"?: AepTotalTokens;
  "aep.total_cost_usd"?: AepTotalCostUsd;
  "aep.total_turns"?: AepTotalTurns;
  "aep.duration_ms"?: AepDurationMs;
  "aep.output"?: unknown;
  [k: string]: unknown;
}
/**
 * Cumulative run-state used in cost_recorded and agent_stopped data.
 * Open model — supervisor SDKs can carry implementation-specific fields.
 */
export interface RunStateSnapshot {
  total_cost_usd: TotalCostUsd;
  total_tokens: TotalTokens;
  total_turns: TotalTurns;
  tokens_input_total?: TokensInputTotal;
  tokens_output_total?: TokensOutputTotal;
  tokens_cache_read_total?: TokensCacheReadTotal;
  tokens_cache_write_total?: TokensCacheWriteTotal;
  tools_invoked?: ToolsInvoked;
  started_at?: StartedAt;
  duration_ms?: DurationMs;
  [k: string]: unknown;
}
export interface ModelTurnStartedEvent {
  specversion?: Specversion2;
  id?: Id2;
  time?: Time2;
  subject?: Subject2;
  datacontenttype?: Datacontenttype2;
  dataschema?: Dataschema2;
  "aep.correlation_id"?: AepCorrelationId2;
  type?: Type2;
  source?: Source2;
  data: ModelTurnStartedData;
}
export interface ModelTurnStartedData {
  trace_id: TraceId2;
  span_id: SpanId2;
  parent_span_id: ParentSpanId2;
  step: Step;
  "aep.context_messages"?: AepContextMessages;
  "gen_ai.request.stream"?: GenAiRequestStream;
  [k: string]: unknown;
}
export interface ModelTurnEndedEvent {
  specversion?: Specversion3;
  id?: Id3;
  time?: Time3;
  subject?: Subject3;
  datacontenttype?: Datacontenttype3;
  dataschema?: Dataschema3;
  "aep.correlation_id"?: AepCorrelationId3;
  type?: Type3;
  source?: Source3;
  data: ModelTurnEndedData;
}
export interface ModelTurnEndedData {
  trace_id: TraceId3;
  span_id: SpanId3;
  parent_span_id: ParentSpanId3;
  step: Step1;
  duration_ms: DurationMs1;
  "gen_ai.provider.name"?: GenAiProviderName1;
  "gen_ai.request.model"?: GenAiRequestModel1;
  "gen_ai.response.model"?: GenAiResponseModel;
  "gen_ai.response.finish_reasons"?: GenAiResponseFinishReasons;
  "gen_ai.response.time_to_first_chunk"?: GenAiResponseTimeToFirstChunk;
  "gen_ai.usage.input_tokens": GenAiUsageInputTokens;
  "gen_ai.usage.output_tokens": GenAiUsageOutputTokens;
  "gen_ai.usage.cache_read.input_tokens"?: GenAiUsageCacheReadInputTokens;
  "gen_ai.usage.cache_creation.input_tokens"?: GenAiUsageCacheCreationInputTokens;
  "gen_ai.usage.reasoning.output_tokens"?: GenAiUsageReasoningOutputTokens;
  "aep.cost_usd": AepCostUsd;
  "aep.cost.source"?: AepCostSource;
  [k: string]: unknown;
}
export interface ToolInvokedEvent {
  specversion?: Specversion4;
  id?: Id4;
  time?: Time4;
  subject?: Subject4;
  datacontenttype?: Datacontenttype4;
  dataschema?: Dataschema4;
  "aep.correlation_id"?: AepCorrelationId4;
  type?: Type4;
  source?: Source4;
  data: ToolInvokedData;
}
export interface ToolInvokedData {
  trace_id: TraceId4;
  span_id: SpanId4;
  parent_span_id: ParentSpanId4;
  step: Step2;
  "gen_ai.tool.call.id": GenAiToolCallId;
  "gen_ai.tool.name": GenAiToolName;
  "gen_ai.tool.call.arguments": GenAiToolCallArguments;
  "aep.tool.dispatch_target"?: AepToolDispatchTarget;
  "aep.tool.subtype"?: AepToolSubtype;
  [k: string]: unknown;
}
export interface GenAiToolCallArguments {
  [k: string]: unknown;
}
export interface ToolReturnedEvent {
  specversion?: Specversion5;
  id?: Id5;
  time?: Time5;
  subject?: Subject5;
  datacontenttype?: Datacontenttype5;
  dataschema?: Dataschema5;
  "aep.correlation_id"?: AepCorrelationId5;
  type?: Type5;
  source?: Source5;
  data: ToolReturnedData;
}
export interface ToolReturnedData {
  trace_id: TraceId5;
  span_id: SpanId5;
  parent_span_id: ParentSpanId5;
  step: Step3;
  "gen_ai.tool.call.id": GenAiToolCallId1;
  "gen_ai.tool.name": GenAiToolName1;
  duration_ms: DurationMs2;
  "aep.tool.result.text": AepToolResultText;
  "aep.tool.result.structured"?: unknown;
  "aep.tool.rejected"?: AepToolRejected;
  "aep.tool.rejection_reason"?: AepToolRejectionReason;
  [k: string]: unknown;
}
export interface ToolFailedEvent {
  specversion?: Specversion6;
  id?: Id6;
  time?: Time6;
  subject?: Subject6;
  datacontenttype?: Datacontenttype6;
  dataschema?: Dataschema6;
  "aep.correlation_id"?: AepCorrelationId6;
  type?: Type6;
  source?: Source6;
  data: ToolFailedData;
}
export interface ToolFailedData {
  trace_id: TraceId6;
  span_id: SpanId6;
  parent_span_id: ParentSpanId6;
  step: Step4;
  "gen_ai.tool.call.id": GenAiToolCallId2;
  "gen_ai.tool.name": GenAiToolName2;
  "aep.tool.error": AepToolError;
  "aep.tool.error.code"?: AepToolErrorCode;
  [k: string]: unknown;
}
export interface SubagentInvokedEvent {
  specversion?: Specversion7;
  id?: Id7;
  time?: Time7;
  subject?: Subject7;
  datacontenttype?: Datacontenttype7;
  dataschema?: Dataschema7;
  "aep.correlation_id"?: AepCorrelationId7;
  type?: Type7;
  source?: Source7;
  data: SubagentInvokedData;
}
/**
 * Parent agent delegates to a declared subagent.
 *
 * The event's `span_id` IS the subagent's frame span. Events emitted by
 * the subagent's sub-loop set `parent_span_id` to this frame (or chain
 * through descendants of it), so the trajectory reconstructs as a nested
 * tree. Per OTel GenAI semconv §invoke_agent, `gen_ai.operation.name` is
 * `invoke_agent` and `gen_ai.agent.name` carries the subagent's declared
 * name.
 */
export interface SubagentInvokedData {
  trace_id: TraceId7;
  span_id: SpanId7;
  parent_span_id: ParentSpanId7;
  step: Step5;
  "gen_ai.agent.name": GenAiAgentName;
  "gen_ai.agent.description"?: GenAiAgentDescription;
  "gen_ai.operation.name"?: GenAiOperationName1;
  "aep.subagent.invocation_id": AepSubagentInvocationId;
  "aep.subagent.input": AepSubagentInput;
  [k: string]: unknown;
}
export interface AepSubagentInput {
  [k: string]: unknown;
}
export interface SubagentReturnedEvent {
  specversion?: Specversion8;
  id?: Id8;
  time?: Time8;
  subject?: Subject8;
  datacontenttype?: Datacontenttype8;
  dataschema?: Dataschema8;
  "aep.correlation_id"?: AepCorrelationId8;
  type?: Type8;
  source?: Source8;
  data: SubagentReturnedData;
}
/**
 * Closes the subagent's frame. `span_id` matches the corresponding
 * `subagent_invoked` event so consumers can pair them. `aep.subagent.usage`
 * rolls up the subagent's own consumption (cost, tokens, turns) — this
 * rollup is also reflected in the parent run's cumulative state, but the
 * breakdown is preserved here so consumers can attribute spend to the
 * subagent that incurred it.
 */
export interface SubagentReturnedData {
  trace_id: TraceId8;
  span_id: SpanId8;
  parent_span_id: ParentSpanId8;
  step: Step6;
  "gen_ai.agent.name": GenAiAgentName1;
  "aep.subagent.invocation_id": AepSubagentInvocationId1;
  duration_ms: DurationMs3;
  "aep.subagent.result.text": AepSubagentResultText;
  "aep.subagent.result.structured"?: unknown;
  "aep.subagent.reason": StopReason;
  "aep.subagent.usage": RunStateSnapshot;
  [k: string]: unknown;
}
export interface SubagentFailedEvent {
  specversion?: Specversion9;
  id?: Id9;
  time?: Time9;
  subject?: Subject9;
  datacontenttype?: Datacontenttype9;
  dataschema?: Dataschema9;
  "aep.correlation_id"?: AepCorrelationId9;
  type?: Type9;
  source?: Source9;
  data: SubagentFailedData;
}
/**
 * Subagent invocation errored. The parent treats the error as a
 * tool-call failure: the model receives an `Error: ...` string in place
 * of the result and may retry or proceed.
 */
export interface SubagentFailedData {
  trace_id: TraceId9;
  span_id: SpanId9;
  parent_span_id: ParentSpanId9;
  step: Step7;
  "gen_ai.agent.name": GenAiAgentName2;
  "aep.subagent.invocation_id": AepSubagentInvocationId2;
  duration_ms: DurationMs4;
  "aep.subagent.error": AepSubagentError;
  "aep.subagent.error.code"?: AepSubagentErrorCode;
  [k: string]: unknown;
}
export interface TextEmittedEvent {
  specversion?: Specversion10;
  id?: Id10;
  time?: Time10;
  subject?: Subject10;
  datacontenttype?: Datacontenttype10;
  dataschema?: Dataschema10;
  "aep.correlation_id"?: AepCorrelationId10;
  type?: Type10;
  source?: Source10;
  data: TextEmittedData;
}
export interface TextEmittedData {
  trace_id: TraceId10;
  span_id: SpanId10;
  parent_span_id: ParentSpanId10;
  step: Step8;
  "aep.text": AepText;
  [k: string]: unknown;
}
export interface ReasoningEmittedEvent {
  specversion?: Specversion11;
  id?: Id11;
  time?: Time11;
  subject?: Subject11;
  datacontenttype?: Datacontenttype11;
  dataschema?: Dataschema11;
  "aep.correlation_id"?: AepCorrelationId11;
  type?: Type11;
  source?: Source11;
  data: ReasoningEmittedData;
}
/**
 * The model produced a reasoning / thinking block during this turn.
 *
 * Distinct from `text_emitted` — reasoning is not user-facing output;
 * it's the model's internal chain-of-thought that some providers
 * expose (Anthropic extended thinking, OpenAI o1/o3 reasoning summaries,
 * etc.). Consumers can filter on this event type to redact / collapse
 * chain-of-thought from displays without losing it from the audit log.
 *
 * `aep.reasoning.signature` rides along when the provider returns a
 * cryptographic signature on the thinking block (Anthropic does this
 * for redacted_thinking blocks); empty when the provider doesn't.
 * `aep.reasoning.redacted` flags blocks the provider has returned in
 * encrypted-only form (no plaintext) — the wire still records the
 * occurrence so audit consumers can count thinking turns.
 */
export interface ReasoningEmittedData {
  trace_id: TraceId11;
  span_id: SpanId11;
  parent_span_id: ParentSpanId11;
  step: Step9;
  "aep.reasoning.text": AepReasoningText;
  "aep.reasoning.signature"?: AepReasoningSignature;
  "aep.reasoning.redacted"?: AepReasoningRedacted;
  [k: string]: unknown;
}
export interface RefusalRecordedEvent {
  specversion?: Specversion12;
  id?: Id12;
  time?: Time12;
  subject?: Subject12;
  datacontenttype?: Datacontenttype12;
  dataschema?: Dataschema12;
  "aep.correlation_id"?: AepCorrelationId12;
  type?: Type12;
  source?: Source12;
  data: RefusalRecordedData;
}
/**
 * The model declined to generate a response or had its output filtered.
 *
 * Common across providers but each exposes a different slice:
 *   - Anthropic:  `stop_reason="refusal"` (or `"sensitive"`), no
 *                 structured category, sometimes a refusal-flavored
 *                 text block.
 *   - OpenAI:     `finish_reason="content_filter"` plus a dedicated
 *                 `refusal` field on the assistant message containing
 *                 the model's refusal text.
 *   - Gemini:     `finishReason` enum (`SAFETY`, `RECITATION`,
 *                 `BLOCKLIST`, `PROHIBITED_CONTENT`, `SPII`) plus
 *                 per-category `safetyRatings`.
 *
 * AEP normalizes to a provider-agnostic shape: `reason` is the
 * provider's raw code (verbatim, so audit pipelines can match exact
 * upstream strings), `message` is the model's refusal text when given,
 * `category` is the provider's safety category (free-form because
 * every provider names them differently), `provider` lets downstream
 * consumers normalize the reason code without context-guessing.
 *
 * A refusal terminates the turn — the model produced no useful text or
 * tool call. Whether the *run* terminates is a runner decision (the
 * reference runner stops with `StopReason.refused`); a higher-level
 * supervisor may choose to reset history and retry.
 */
export interface RefusalRecordedData {
  trace_id: TraceId12;
  span_id: SpanId12;
  parent_span_id: ParentSpanId12;
  step: Step10;
  "aep.refusal.reason": AepRefusalReason;
  "aep.refusal.message"?: AepRefusalMessage;
  "aep.refusal.category"?: AepRefusalCategory;
  "aep.refusal.provider"?: AepRefusalProvider;
  [k: string]: unknown;
}
export interface CostRecordedEvent {
  specversion?: Specversion13;
  id?: Id13;
  time?: Time13;
  subject?: Subject13;
  datacontenttype?: Datacontenttype13;
  dataschema?: Dataschema13;
  "aep.correlation_id"?: AepCorrelationId13;
  type?: Type13;
  source?: Source13;
  data: CostRecordedData;
}
export interface CostRecordedData {
  trace_id: TraceId13;
  span_id: SpanId13;
  parent_span_id: ParentSpanId13;
  "aep.state": RunStateSnapshot;
  "aep.cost.source"?: AepCostSource1;
  [k: string]: unknown;
}
export interface SkillLoadedEvent {
  specversion?: Specversion14;
  id?: Id14;
  time?: Time14;
  subject?: Subject14;
  datacontenttype?: Datacontenttype14;
  dataschema?: Dataschema14;
  "aep.correlation_id"?: AepCorrelationId14;
  type?: Type14;
  source?: Source14;
  data: SkillLoadedData;
}
export interface SkillLoadedData {
  trace_id: TraceId14;
  span_id: SpanId14;
  parent_span_id: ParentSpanId14;
  step: Step11;
  "aep.skill.name": AepSkillName;
  "aep.skill.source"?: AepSkillSource;
  [k: string]: unknown;
}
export interface SkillExecutedEvent {
  specversion?: Specversion15;
  id?: Id15;
  time?: Time15;
  subject?: Subject15;
  datacontenttype?: Datacontenttype15;
  dataschema?: Dataschema15;
  "aep.correlation_id"?: AepCorrelationId15;
  type?: Type15;
  source?: Source15;
  data: SkillExecutedData;
}
export interface SkillExecutedData {
  trace_id: TraceId15;
  span_id: SpanId15;
  parent_span_id: ParentSpanId15;
  step: Step12;
  "aep.skill.name": AepSkillName1;
  [k: string]: unknown;
}
export interface ErrorOccurredEvent {
  specversion?: Specversion16;
  id?: Id16;
  time?: Time16;
  subject?: Subject16;
  datacontenttype?: Datacontenttype16;
  dataschema?: Dataschema16;
  "aep.correlation_id"?: AepCorrelationId16;
  type?: Type16;
  source?: Source16;
  data: ErrorOccurredData;
}
export interface ErrorOccurredData {
  trace_id: TraceId16;
  span_id: SpanId16;
  parent_span_id: ParentSpanId16;
  "aep.error.code": ErrorCode;
  "aep.error.message": AepErrorMessage;
  [k: string]: unknown;
}
/**
 * Agent calls into an external service (supervisor RPC or MCP server).
 *
 * `source` is `aep://runner` because the runner emits this event when the
 * agent decides to call a tool whose implementation is external.
 */
export interface ToolExecRequestEvent {
  specversion?: Specversion17;
  id?: Id17;
  time?: Time17;
  subject?: Subject17;
  datacontenttype?: Datacontenttype17;
  dataschema?: Dataschema17;
  "aep.correlation_id"?: AepCorrelationId17;
  type?: Type17;
  source?: Source17;
  data: ToolExecRequestData;
}
/**
 * Wraps the JSON-RPC request alongside AEP-side bookkeeping.
 *
 * `gen_ai.tool.name` is duplicated at the top of `data` (OTel convention)
 * even though it's also inside `rpc.params.name` per MCP — this keeps tool
 * filtering on the trajectory uniform across `tool_invoked` /
 * `tool_exec_request` / `tool_returned`.
 */
export interface ToolExecRequestData {
  trace_id: TraceId17;
  span_id: SpanId17;
  parent_span_id: ParentSpanId17;
  step: Step13;
  "aep.request_id": AepRequestId;
  "gen_ai.tool.call.id": GenAiToolCallId3;
  "aep.timeout_ms": AepTimeoutMs;
  "aep.tool.dispatch_target": AepToolDispatchTarget1;
  "aep.mcp_server_id"?: AepMcpServerId1;
  "gen_ai.tool.name": GenAiToolName3;
  rpc: JsonRpcRequestPayload;
  [k: string]: unknown;
}
/**
 * JSON-RPC 2.0 request payload — what tool_exec_request.data carries.
 *
 * Per MCP convention, `method` is `"tools/call"` and `params` is
 * `{name, arguments}`.
 */
export interface JsonRpcRequestPayload {
  jsonrpc?: Jsonrpc;
  id: Id18;
  method: Method;
  params: Params;
  [k: string]: unknown;
}
export interface Params {
  [k: string]: unknown;
}
/**
 * RPC reply recorded into the trajectory verbatim. `source` is the URI
 * of the responding service: `aep://supervisor` or `aep://mcp/<server_id>`.
 */
export interface ToolExecResolvedEvent {
  specversion?: Specversion18;
  id?: Id19;
  time?: Time18;
  subject?: Subject18;
  datacontenttype?: Datacontenttype18;
  dataschema?: Dataschema18;
  "aep.correlation_id"?: AepCorrelationId18;
  type?: Type18;
  source: Source18;
  data: ToolExecResolvedData;
}
/**
 * Wraps the JSON-RPC response. `source` URI on the envelope identifies
 * who answered (supervisor or mcp/<server_id>).
 *
 * `gen_ai.tool.name` echoes the request's tool name for observability —
 * consumers shouldn't need to cross-reference the request to filter replies.
 */
export interface ToolExecResolvedData {
  trace_id: TraceId18;
  span_id: SpanId18;
  parent_span_id: ParentSpanId18;
  "aep.request_id": AepRequestId1;
  "gen_ai.tool.name"?: GenAiToolName4;
  rpc: JsonRpcResponsePayload;
  [k: string]: unknown;
}
/**
 * JSON-RPC 2.0 response payload — what tool_exec_resolved.data carries.
 *
 * Exactly one of `result` or `error` MUST be present per the JSON-RPC spec.
 */
export interface JsonRpcResponsePayload {
  jsonrpc?: Jsonrpc1;
  id?: Id20;
  result?: unknown;
  error?: JsonRpcError | null;
  [k: string]: unknown;
}
export interface JsonRpcError {
  code: Code;
  message: Message;
  data?: unknown;
  [k: string]: unknown;
}
export interface ToolExecTimedOutEvent {
  specversion?: Specversion19;
  id?: Id21;
  time?: Time19;
  subject?: Subject19;
  datacontenttype?: Datacontenttype19;
  dataschema?: Dataschema19;
  "aep.correlation_id"?: AepCorrelationId19;
  type?: Type19;
  source?: Source19;
  data: ToolExecTimedOutData;
}
export interface ToolExecTimedOutData {
  trace_id: TraceId19;
  span_id: SpanId19;
  parent_span_id: ParentSpanId19;
  step: Step14;
  "aep.request_id": AepRequestId2;
  "gen_ai.tool.call.id": GenAiToolCallId4;
  "gen_ai.tool.name": GenAiToolName5;
  "aep.timeout_ms": AepTimeoutMs1;
  [k: string]: unknown;
}
/**
 * Runner asks the supervisor to approve (or deny) something —
 * typically a tool dispatch gated by a pre_tool: + approval-source
 * verifier. The supervisor MUST reply with `approval_resolved`.
 */
export interface ApprovalRequestedEvent {
  specversion?: Specversion20;
  id?: Id22;
  time?: Time20;
  subject?: Subject20;
  datacontenttype?: Datacontenttype20;
  dataschema?: Dataschema20;
  "aep.correlation_id"?: AepCorrelationId20;
  type?: Type20;
  source?: Source20;
  data: ApprovalRequestedData;
}
/**
 * Runner emits this when an approval-source verifier fires.
 *
 * Carries the context the supervisor needs to decide: which verifier
 * requested it, the optional prompt, and (for `pre_tool:<name>`
 * gates) the tool call this approval covers. The supervisor MUST
 * reply with an `approval_resolved` referencing the same
 * `aep.approval.id` within `aep.timeout_ms`; missing replies are
 * treated as denials.
 */
export interface ApprovalRequestedData {
  trace_id: TraceId20;
  span_id: SpanId20;
  parent_span_id: ParentSpanId20;
  step: Step15;
  "aep.approval.id": AepApprovalId;
  "aep.timeout_ms": AepTimeoutMs2;
  "aep.verifier.name": AepVerifierName;
  "aep.approval.prompt"?: AepApprovalPrompt;
  "gen_ai.tool.name"?: GenAiToolName6;
  "gen_ai.tool.call.id"?: GenAiToolCallId5;
  "gen_ai.tool.call.arguments"?: GenAiToolCallArguments1;
  [k: string]: unknown;
}
/**
 * Supervisor's decision recorded into the trajectory verbatim.
 * `source` is `aep://supervisor`.
 */
export interface ApprovalResolvedEvent {
  specversion?: Specversion21;
  id?: Id23;
  time?: Time21;
  subject?: Subject21;
  datacontenttype?: Datacontenttype21;
  dataschema?: Dataschema21;
  "aep.correlation_id"?: AepCorrelationId21;
  type?: Type21;
  source: Source21;
  data: ApprovalResolvedData;
}
/**
 * Supervisor's decision for a pending `approval_requested`.
 *
 * `approved` is the load-bearing field. `reason` is free-text
 * intended for the trajectory consumer (and for surfacing to the
 * model on `pre_tool:` denials via the resulting `tool_failed.error`).
 */
export interface ApprovalResolvedData {
  trace_id: TraceId21;
  span_id: SpanId21;
  parent_span_id: ParentSpanId21;
  "aep.approval.id": AepApprovalId1;
  "aep.approval.approved": AepApprovalApproved;
  "aep.approval.reason"?: AepApprovalReason;
  [k: string]: unknown;
}
export interface VerifierEvaluatedEvent {
  specversion?: Specversion22;
  id?: Id24;
  time?: Time22;
  subject?: Subject22;
  datacontenttype?: Datacontenttype22;
  dataschema?: Dataschema22;
  "aep.correlation_id"?: AepCorrelationId22;
  type?: Type22;
  source?: Source22;
  data: VerifierEvaluatedData;
}
/**
 * The result of a deterministic Boolean check.
 */
export interface VerifierEvaluatedData {
  trace_id: TraceId22;
  span_id: SpanId22;
  parent_span_id: ParentSpanId22;
  "aep.verifier.name": AepVerifierName1;
  "aep.verifier.passed": AepVerifierPassed;
  "aep.verifier.duration_ms": AepVerifierDurationMs;
  step?: Step16;
  "aep.verifier.error"?: VerifierError | null;
  "aep.verifier.subject_call_ids"?: AepVerifierSubjectCallIds;
  "aep.verifier.subject_request_ids"?: AepVerifierSubjectRequestIds;
  "aep.verifier.data"?: AepVerifierData;
  [k: string]: unknown;
}
export interface McpServerConnectedEvent {
  specversion?: Specversion23;
  id?: Id25;
  time?: Time23;
  subject?: Subject23;
  datacontenttype?: Datacontenttype23;
  dataschema?: Dataschema23;
  "aep.correlation_id"?: AepCorrelationId23;
  type?: Type23;
  source?: Source23;
  data: McpServerConnectedData;
}
export interface McpServerConnectedData {
  trace_id: TraceId23;
  span_id: SpanId23;
  parent_span_id: ParentSpanId23;
  "aep.mcp.server_id": AepMcpServerId2;
  "aep.mcp.protocol_version": AepMcpProtocolVersion;
  "aep.mcp.tool_count": AepMcpToolCount;
  "aep.mcp.server_name"?: AepMcpServerName;
  "aep.mcp.server_version"?: AepMcpServerVersion;
  "aep.mcp.tools"?: AepMcpTools;
  "aep.mcp.status"?: AepMcpStatus;
  "aep.mcp.error"?: AepMcpError;
  [k: string]: unknown;
}
export interface McpServerDisconnectedEvent {
  specversion?: Specversion24;
  id?: Id26;
  time?: Time24;
  subject?: Subject24;
  datacontenttype?: Datacontenttype24;
  dataschema?: Dataschema24;
  "aep.correlation_id"?: AepCorrelationId24;
  type?: Type24;
  source?: Source24;
  data: McpServerDisconnectedData;
}
export interface McpServerDisconnectedData {
  trace_id: TraceId24;
  span_id: SpanId24;
  parent_span_id: ParentSpanId24;
  "aep.mcp.server_id": AepMcpServerId3;
  "aep.mcp.disconnect_reason": AepMcpDisconnectReason;
  "aep.mcp.disconnect_message"?: AepMcpDisconnectMessage;
  [k: string]: unknown;
}
