/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Supervisor (or MCP server) → runner reply. v0.1 carries only `aep.tool_exec_resolved` events. `source` is `aep://supervisor` for supervisor-routed RPCs or `aep://mcp/<server_id>` for MCP-server-routed RPCs. The payload's `data.rpc` is a JSON-RPC 2.0 response.
 */
export type AEPV01SupervisorMessage = ToolExecResolvedEvent | ApprovalResolvedEvent;
export type Specversion = "1.0";
export type Id = string;
export type Time = string;
export type Subject = string | null;
export type Datacontenttype = string | null;
export type Dataschema = string | null;
export type AepCorrelationId = string | null;
export type Type = "aep.tool_exec_resolved";
export type Source = string;
export type TraceId = string;
export type SpanId = string;
export type ParentSpanId = string;
export type AepRequestId = string;
export type GenAiToolName = string | null;
export type Jsonrpc = "2.0";
export type Id1 = string | number | null;
export type Code = number;
export type Message = string;
export type Specversion1 = "1.0";
export type Id2 = string;
export type Time1 = string;
export type Subject1 = string | null;
export type Datacontenttype1 = string | null;
export type Dataschema1 = string | null;
export type AepCorrelationId1 = string | null;
export type Type1 = "aep.approval_resolved";
export type Source1 = string;
export type TraceId1 = string;
export type SpanId1 = string;
export type ParentSpanId1 = string;
export type AepApprovalId = string;
export type AepApprovalApproved = boolean;
export type AepApprovalReason = string | null;

/**
 * RPC reply recorded into the trajectory verbatim. `source` is the URI
 * of the responding service: `aep://supervisor` or `aep://mcp/<server_id>`.
 */
export interface ToolExecResolvedEvent {
  specversion?: Specversion;
  id?: Id;
  time?: Time;
  subject?: Subject;
  datacontenttype?: Datacontenttype;
  dataschema?: Dataschema;
  "aep.correlation_id"?: AepCorrelationId;
  type?: Type;
  source: Source;
  data: ToolExecResolvedData;
}
/**
 * Wraps the JSON-RPC response. `source` URI on the envelope identifies
 * who answered (supervisor or mcp/<server_id>).
 *
 * `gen_ai.tool.name` echoes the request's tool name for observability —
 * consumers shouldn't need to cross-reference the request to filter replies.
 */
export interface ToolExecResolvedData {
  trace_id: TraceId;
  span_id: SpanId;
  parent_span_id: ParentSpanId;
  "aep.request_id": AepRequestId;
  "gen_ai.tool.name"?: GenAiToolName;
  rpc: JsonRpcResponsePayload;
  [k: string]: unknown;
}
/**
 * JSON-RPC 2.0 response payload — what tool_exec_resolved.data carries.
 *
 * Exactly one of `result` or `error` MUST be present per the JSON-RPC spec.
 */
export interface JsonRpcResponsePayload {
  jsonrpc?: Jsonrpc;
  id?: Id1;
  result?: unknown;
  error?: JsonRpcError | null;
  [k: string]: unknown;
}
export interface JsonRpcError {
  code: Code;
  message: Message;
  data?: unknown;
  [k: string]: unknown;
}
/**
 * Supervisor's decision recorded into the trajectory verbatim.
 * `source` is `aep://supervisor`.
 */
export interface ApprovalResolvedEvent {
  specversion?: Specversion1;
  id?: Id2;
  time?: Time1;
  subject?: Subject1;
  datacontenttype?: Datacontenttype1;
  dataschema?: Dataschema1;
  "aep.correlation_id"?: AepCorrelationId1;
  type?: Type1;
  source: Source1;
  data: ApprovalResolvedData;
}
/**
 * Supervisor's decision for a pending `approval_requested`.
 *
 * `approved` is the load-bearing field. `reason` is free-text
 * intended for the trajectory consumer (and for surfacing to the
 * model on `pre_tool:` denials via the resulting `tool_failed.error`).
 */
export interface ApprovalResolvedData {
  trace_id: TraceId1;
  span_id: SpanId1;
  parent_span_id: ParentSpanId1;
  "aep.approval.id": AepApprovalId;
  "aep.approval.approved": AepApprovalApproved;
  "aep.approval.reason"?: AepApprovalReason;
  [k: string]: unknown;
}
