/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type AgentName = string;
export type AgentVersion = string;
export type SpecVersion = "0.1";
export type DefaultModel = string | null;
export type SupportedModels = string[] | null;
export type SystemPrompt = string | null;
export type Prompt = string | null;
export type McpServers = McpServerDecl[] | null;
export type Id = string;
export type Name = string | null;
export type Description = string | null;
export type Status = ("connected" | "failed" | "needs-auth" | "pending" | "disabled") | null;
export type Tools = ToolDecl[] | null;
export type Name1 = string;
export type Description1 = string | null;
export type Inputschema = {
  [k: string]: unknown;
} | null;
export type Outputschema = {
  [k: string]: unknown;
} | null;
export type AvpMcpServerId = string | null;
export type Subagents = SubagentDecl[] | null;
export type Name2 = string;
export type Description2 = string | null;
export type Inputschema1 = {
  [k: string]: unknown;
} | null;
export type AvpAgentType = string | null;
export type Skills = SkillDecl[] | null;
export type Name3 = string;
export type Description3 = string | null;
export type Version = string | null;
export type AvpSource = string | null;
export type Capabilities = string[] | null;

/**
 * The agent's self-description. Enumerates built-in tools, subagents, and skills triggerable without supervisor configuration, plus the agent's identity, capabilities, and supported models. Pre-flight (`<agent> describe` stdout) and run-time (`agent_described.data['avp.descriptor']`) views MUST match for the same agent build. See spec/v0.1/agent-descriptor.md.
 */
export interface AVPV01AgentDescriptor {
  agent_name: AgentName;
  agent_version: AgentVersion;
  spec_version: SpecVersion;
  default_model?: DefaultModel;
  supported_models?: SupportedModels;
  system_prompt?: SystemPrompt;
  prompt?: Prompt;
  mcp_servers?: McpServers;
  tools?: Tools;
  subagents?: Subagents;
  skills?: Skills;
  capabilities?: Capabilities;
}
/**
 * MCP server descriptor in `AgentDescriptor.mcp_servers` and
 * `agent_started.data["avp.mcp_servers"]`: identity + terminal dial status.
 *
 * Connection material (URLs, auth, command-lines) stays inside the agent
 * process and is NOT carried on the descriptor wire. The descriptor
 * records the server's id, optional display name, optional description,
 * and the terminal dial status when known. The tools the server surfaces
 * are enumerated in the sibling `tools[]` list with `avp.mcp_server_id`
 * set to this server's `id`; only `status: "connected"` servers
 * contribute tools.
 *
 * `id` is the agent's correlation key for this server across the wire
 * (descriptor entry, tool entry's `avp.mcp_server_id`). It is intentionally
 * looser than `Commission.McpServerRef.id`: the descriptor enumerates BOTH
 * Commission-resolved servers (where `id` is the supervisor-authored slug)
 * AND agent-baked-in / environment-resident servers (where `id` is whatever
 * the environment names them, e.g. `"claude.ai Dashboard Builder"`). Forcing
 * a slug here would either lose fidelity or require every agent to invent
 * the same slugification rule. Commission-authored ids stay slug-clean by
 * virtue of `Commission.McpServerRef.id`'s pattern; descriptor ids must
 * only be non-empty.
 *
 * `name` is the display name when the environment provides one distinct
 * from `id` (typical for Commission-resolved servers: `id` is the
 * Commission slug, `name` is the human-readable label from the resolved
 * config). For environment-resident servers whose only identifier is
 * the display name, `id` carries that string and `name` is omitted.
 *
 * `status` records the dial outcome at startup. Pre-flight `<agent> describe`
 * MAY omit it (no dial has happened); on-the-wire `agent_described` and
 * `agent_started` populate it. Values mirror the Claude Agent SDK's
 * `McpServerStatus.status` enum.
 *
 * This interface was referenced by `AVPV01AgentDescriptor`'s JSON-Schema
 * via the `definition` "McpServerDecl".
 */
export interface McpServerDecl {
  id: Id;
  name?: Name;
  description?: Description;
  status?: Status;
  [k: string]: unknown;
}
/**
 * Tool descriptor used by `AgentDescriptor.tools` and
 * `agent_started.data["avp.tools"]`.
 *
 * MCP-shaped: `name` plus optional `description`, `inputSchema`, and
 * `outputSchema`. The decl describes a single tool's model-facing
 * identity, and agents SHOULD carry `description` / `inputSchema` /
 * `outputSchema` exactly as surfaced to the model when the runtime
 * exposes them: the tool catalog is the dominant fixed input-token
 * cost of every turn, and name-only decls make that cost
 * unattributable. Name-only entries remain valid (honest-null when
 * the wrapped runtime doesn't expose the catalog text). Dispatch is
 * discriminated by `avp.mcp_server_id`: when set, the tool is sourced
 * from the MCP server with that `id` in `mcp_servers[]`; when absent,
 * the tool runs locally in the agent's process. The per-invocation
 * discriminator `avp.tool.dispatch_target` on `tool_invoked` mirrors
 * presence of this field.
 *
 * This interface was referenced by `AVPV01AgentDescriptor`'s JSON-Schema
 * via the `definition` "ToolDecl".
 */
export interface ToolDecl {
  name: Name1;
  description?: Description1;
  inputSchema?: Inputschema;
  outputSchema?: Outputschema;
  "avp.mcp_server_id"?: AvpMcpServerId;
  [k: string]: unknown;
}
/**
 * Subagent descriptor in `agent_started.data["avp.subagents"]`: what the
 * parent model sees when deciding whether to delegate. Same MCP-shaped
 * triple (`name`, `description`, `inputSchema`) tools use, so adapters
 * can render subagents to the model's tool list with no translation.
 *
 * `description` is optional to match `ToolDecl`: when surfacing a
 * agent-built-in subagent (e.g. the Claude Agent SDK's `general-purpose`)
 * the agent has authoritative knowledge of the name but not the prose
 * description. Honest-null beats authored-prose-that-drifts.
 *
 * This interface was referenced by `AVPV01AgentDescriptor`'s JSON-Schema
 * via the `definition` "SubagentDecl".
 */
export interface SubagentDecl {
  name: Name2;
  description?: Description2;
  inputSchema?: Inputschema1;
  "avp.agent_type"?: AvpAgentType;
  [k: string]: unknown;
}
/**
 * Skill descriptor in `AgentDescriptor.skills` and
 * `agent_started.data["avp.skills"]`: name plus optional metadata about each
 * skill the agent ships with or has loaded for the run.
 *
 * Replaces the v0.1-prototype `list[str]` shape (names-only) with a
 * structured decl matching `ToolDecl` / `SubagentDecl`. Description
 * comes from the SKILL.md frontmatter when the agent surfaces it
 * (e.g. via `ClaudeSDKClient.get_context_usage()` which returns a
 * `skills` breakdown including frontmatter); `version` is the skill's
 * own version when known; `avp.source` is the SKILL.md path / URI.
 *
 * All fields except `name` are optional so agents that only know
 * the name (Commission-declared without enrichment) still emit valid
 * decls.
 *
 * This interface was referenced by `AVPV01AgentDescriptor`'s JSON-Schema
 * via the `definition` "SkillDecl".
 */
export interface SkillDecl {
  name: Name3;
  description?: Description3;
  version?: Version;
  "avp.source"?: AvpSource;
  [k: string]: unknown;
}
