/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type SchemaVersion = "0.1";
export type RunId = string;
export type Name = string;
export type Version = string | null;
export type McpServers = (McpServerHttp | McpServerStdio)[] | null;
export type Id = string;
export type Type = "http";
export type Url = string;
export type Headers = {
  [k: string]: string;
} | null;
export type Id1 = string;
export type Type1 = "stdio";
/**
 * @minItems 1
 */
export type Command = [string, ...string[]];
export type Args = string[] | null;
export type Env = {
  [k: string]: string;
} | null;
export type Skills = Skill[] | null;
export type Id2 = string;
export type EnabledBuiltinTools = string[] | null;
export type EnabledBuiltinSubagents = string[] | null;
export type EnabledBuiltinSkills = string[] | null;
export type EnabledBuiltinMcpServers = string[] | null;
export type OutputSchema = {
  [k: string]: unknown;
} | null;
export type Prompt = string | null;
export type SystemPrompt = string | null;
export type Model = string | null;
export type ThreadId = string | null;
export type Tags = string[] | null;
export type Meta = {
  [k: string]: unknown;
} | null;

/**
 * Supervisor → agent setup message. Declares prompt, model, and supervisor-managed assets (mcp_servers, skills, subagents) as opaque {id, ref} pairs the agent dereferences via the AVP Resolver API at startup. Sent once at startup. See spec/v0.1/commission.md.
 */
export interface AVPV01Commission {
  schema_version: SchemaVersion;
  run_id: RunId;
  supervisor?: SupervisorPreamble | null;
  mcp_servers?: McpServers;
  skills?: Skills;
  enabled_builtin_tools?: EnabledBuiltinTools;
  enabled_builtin_subagents?: EnabledBuiltinSubagents;
  enabled_builtin_skills?: EnabledBuiltinSkills;
  enabled_builtin_mcp_servers?: EnabledBuiltinMcpServers;
  output_schema?: OutputSchema;
  prompt?: Prompt;
  system_prompt?: SystemPrompt;
  model?: Model;
  thread_id?: ThreadId;
  tags?: Tags;
  meta?: Meta;
}
/**
 * Identifies the supervisor that is requesting the run.
 *
 * Carried inside `Commission.supervisor` and projected onto the
 * `run_requested` event's `data` (`avp.supervisor.name` +
 * `avp.supervisor.version`) so a trajectory consumer can attribute the
 * run to the originating supervisor without an out-of-band lookup. The
 * event's `source` is `avp://agent` (the agent is the sole producer on
 * the wire); supervisor attribution lives inside `data`.
 *
 * `name` SHOULD be a stable identifier for the supervisor implementation
 * or instance (e.g. `"avp-cli"`, `"acme.scheduler"`).
 * `version` is optional but recommended; it travels with the trajectory
 * and lets auditors correlate a run with the exact supervisor build
 * that requested it.
 *
 * This interface was referenced by `AVPV01Commission`'s JSON-Schema
 * via the `definition` "SupervisorPreamble".
 */
export interface SupervisorPreamble {
  name: Name;
  version?: Version;
}
/**
 * Inline HTTP MCP server entry in Commission.mcp_servers.
 *
 * This interface was referenced by `AVPV01Commission`'s JSON-Schema
 * via the `definition` "McpServerHttp".
 */
export interface McpServerHttp {
  id: Id;
  type: Type;
  url: Url;
  headers?: Headers;
}
/**
 * Inline stdio MCP server entry in Commission.mcp_servers.
 *
 * This interface was referenced by `AVPV01Commission`'s JSON-Schema
 * via the `definition` "McpServerStdio".
 */
export interface McpServerStdio {
  id: Id1;
  type: Type1;
  command: Command;
  args?: Args;
  env?: Env;
}
/**
 * Inline skill entry in Commission.skills.
 *
 * This interface was referenced by `AVPV01Commission`'s JSON-Schema
 * via the `definition` "Skill".
 */
export interface Skill {
  id: Id2;
  files: Files;
}
export interface Files {
  [k: string]: string;
}
