"""Run history backing `avp eval list` / `view` / `clear` + voyage-id minting."""

from __future__ import annotations

from avp_cli import state


def _seed_traj(d) -> None:
    d.mkdir(parents=True, exist_ok=True)
    (d / "trajectories.json").write_text("{}")


def test_recent_runs_newest_first_deduped_and_existing(tmp_path) -> None:
    home = tmp_path / "home"
    a, b = tmp_path / "runA", tmp_path / "runB"
    _seed_traj(a)
    _seed_traj(b)
    state.record_run(
        run_id="a1", out_dir=a, dataset="d1", agents=["goose"], commissions=["x"], home=home
    )
    state.record_run(
        run_id="b1", out_dir=b, dataset="d2", agents=["claude-code"], commissions=["y"], home=home
    )
    # a second run into the same dir A — dedup should keep one A, and A is now newest
    state.record_run(
        run_id="a2", out_dir=a, dataset="d1", agents=["goose"], commissions=["x", "z"], home=home
    )

    runs = state.recent_runs(home=home)
    assert [r["out_dir"] for r in runs] == [
        str(a.resolve()),
        str(b.resolve()),
    ]  # newest first, deduped
    assert state.last_run(home=home)["dataset"] == "d1"


def test_recent_runs_drops_runs_whose_trajectories_are_gone(tmp_path) -> None:
    home = tmp_path / "home"
    gone = tmp_path / "gone"  # recorded but never has trajectories
    state.record_run(
        run_id="g", out_dir=gone, dataset="d", agents=["goose"], commissions=["x"], home=home
    )
    assert state.recent_runs(home=home) == []
    assert state.last_run(home=home) is None


def test_find_run_resolves_a_live_voyage_id(tmp_path) -> None:
    home = tmp_path / "home"
    a, b = tmp_path / "runA", tmp_path / "runB"
    _seed_traj(a)
    _seed_traj(b)
    state.record_run(
        run_id="swift-harbor",
        out_dir=a,
        dataset="d",
        agents=["goose"],
        commissions=["x"],
        home=home,
    )
    state.record_run(
        run_id="calm-tide", out_dir=b, dataset="d", agents=["goose"], commissions=["x"], home=home
    )
    assert state.find_run("swift-harbor", home=home)["out_dir"] == str(a.resolve())
    assert state.find_run("nope", home=home) is None  # unknown id
    # an id whose trajectories are gone no longer resolves
    state.record_run(
        run_id="lost-reef",
        out_dir=tmp_path / "gone",
        dataset="d",
        agents=["goose"],
        commissions=["x"],
        home=home,
    )
    assert state.find_run("lost-reef", home=home) is None


def test_new_id_is_unique_against_history(tmp_path) -> None:
    home = tmp_path / "home"
    seen: set[str] = set()
    for _ in range(30):
        rid = state.new_id(home=home)
        assert rid not in seen, "new_id must not collide with a recorded id"
        seen.add(rid)
        d = tmp_path / rid
        _seed_traj(d)
        state.record_run(
            run_id=rid, out_dir=d, dataset="d", agents=["goose"], commissions=["x"], home=home
        )


def test_claim_id_slugifies_a_chosen_name(tmp_path) -> None:
    home = tmp_path / "home"
    assert state.claim_id("My Big Test!", home=home) == "my-big-test"


def test_claim_id_suffixes_to_avoid_clobbering(tmp_path) -> None:
    home = tmp_path / "home"
    d = home / "baseline-test"
    _seed_traj(d)
    state.record_run(
        run_id="baseline-test", out_dir=d, dataset="d", agents=["g"], commissions=["x"], home=home
    )
    assert state.claim_id("baseline-test", home=home) == "baseline-test-2"


def test_claim_id_blank_name_autogenerates(tmp_path) -> None:
    home = tmp_path / "home"
    rid = state.claim_id("  !! ", home=home)  # slugs to nothing
    assert "-" in rid and rid not in ("", "-")  # an autogenerated adj-noun


def test_clear_runs_wipes_history_and_dirs(tmp_path) -> None:
    home = tmp_path / "home"
    d = home / "swift-harbor"  # a run dir under the runs home
    _seed_traj(d)
    state.record_run(
        run_id="swift-harbor",
        out_dir=d,
        dataset="d",
        agents=["goose"],
        commissions=["x"],
        home=home,
    )
    assert state.clear_runs(home=home) == 1
    assert not home.exists()
    assert state.recent_runs(home=home) == []


def test_run_trajectories_returns_every_agent_file(tmp_path, monkeypatch) -> None:
    # A multi-agent run has one trajectories file per agent; `view` must surface all
    # of them, not just the newest (the bug where goose got hidden behind claude-code).
    monkeypatch.setenv("AVP_HOME", str(tmp_path / ".avp"))
    from avp_cli import paths
    from avp_cli.cli import _run_trajectories

    d = paths.runs_dir() / "steady-compass"
    d.mkdir(parents=True)
    (d / "trajectories.goose.json").write_text('{"agent": "goose"}')
    (d / "trajectories.claude-code.json").write_text('{"agent": "claude-code"}')
    state.record_run(
        run_id="steady-compass",
        out_dir=d,
        dataset="x",
        agents=["goose", "claude-code"],
        commissions=["a"],
    )
    names = sorted(f.name for f in _run_trajectories("steady-compass"))
    assert names == ["trajectories.claude-code.json", "trajectories.goose.json"]
