/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type AgentName = string;
export type AgentVersion = string;
export type AvpSpecVersion = "0.1";
export type DefaultModel = string | null;
export type SupportedModels = string[] | null;
export type BuiltInTools = _ToolDecl[] | null;
export type Name = string;
export type Description = string | null;
export type Inputschema = {
  [k: string]: unknown;
} | null;
export type AvpDispatchTarget = ("mcp_server" | "local") | null;
export type AvpMcpServerId = string | null;
export type BuiltInSubagents = _SubagentDecl[] | null;
export type Name1 = string;
export type Description1 = string | null;
export type Inputschema1 = {
  [k: string]: unknown;
} | null;
export type AvpAgentType = string | null;
export type BuiltInSkills = _SkillDecl[] | null;
export type Name2 = string;
export type Description2 = string | null;
export type AvpSource = string | null;
export type Capabilities = string[] | null;

/**
 * The agent's self-description. Enumerates built-in tools, subagents, and skills triggerable without supervisor configuration, plus the agent's identity, capabilities, and supported models. Pre-flight (`<agent> describe` stdout) and run-time (`agent_described.data['avp.descriptor']`) views MUST match for the same agent build. See spec/agent-descriptor/v0.1/agent-descriptor.md.
 */
export interface AVPAgentDescriptor {
  agent_name: AgentName;
  agent_version: AgentVersion;
  avp_spec_version: AvpSpecVersion;
  default_model?: DefaultModel;
  supported_models?: SupportedModels;
  built_in_tools?: BuiltInTools;
  built_in_subagents?: BuiltInSubagents;
  built_in_skills?: BuiltInSkills;
  capabilities?: Capabilities;
}
/**
 * Tool descriptor in `agent_started.data.tools`: MCP-shaped plus AVP fields.
 *
 * This interface was referenced by `AVPAgentDescriptor`'s JSON-Schema
 * via the `definition` "_ToolDecl".
 */
export interface _ToolDecl {
  name: Name;
  description?: Description;
  inputSchema?: Inputschema;
  "avp.dispatch_target"?: AvpDispatchTarget;
  "avp.mcp_server_id"?: AvpMcpServerId;
  [k: string]: unknown;
}
/**
 * Subagent descriptor in `agent_started.data.subagents`: what the
 * parent model sees when deciding whether to delegate. Same MCP-shaped
 * triple (`name`, `description`, `inputSchema`) tools use, so adapters
 * can render subagents to the model's tool list with no translation.
 *
 * `description` is optional to match `_ToolDecl`: when surfacing a
 * agent-built-in subagent (e.g. the Claude Agent SDK's `general-purpose`)
 * the agent has authoritative knowledge of the name but not the prose
 * description. Honest-null beats authored-prose-that-drifts.
 *
 * This interface was referenced by `AVPAgentDescriptor`'s JSON-Schema
 * via the `definition` "_SubagentDecl".
 */
export interface _SubagentDecl {
  name: Name1;
  description?: Description1;
  inputSchema?: Inputschema1;
  "avp.agent_type"?: AvpAgentType;
  [k: string]: unknown;
}
/**
 * Skill descriptor in `agent_started.data.skills`: name plus
 * optional metadata about each skill loaded for the run.
 *
 * Replaces the v0.1-prototype `list[str]` shape (names-only) with a
 * structured decl matching `_ToolDecl` / `_SubagentDecl`. Description
 * comes from the SKILL.md frontmatter when the agent surfaces it
 * (e.g. via `ClaudeSDKClient.get_context_usage()` which returns a
 * `skills` breakdown including frontmatter); `avp.source` is the
 * SKILL.md path / URI when known.
 *
 * All fields except `name` are optional so agents that only know
 * the name (Commission-declared without enrichment) still emit valid
 * decls.
 *
 * This interface was referenced by `AVPAgentDescriptor`'s JSON-Schema
 * via the `definition` "_SkillDecl".
 */
export interface _SkillDecl {
  name: Name2;
  description?: Description2;
  "avp.source"?: AvpSource;
  [k: string]: unknown;
}
