/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type AgentName = string;
export type AgentVersion = string;
export type SpecVersion = "0.1";
export type DefaultModel = string | null;
export type SupportedModels = string[] | null;
export type SystemPrompt = string | null;
export type Prompt = string | null;
export type McpServers = McpServerDecl[] | null;
export type Id = string;
export type Name = string | null;
export type Description = string | null;
export type Tools = ToolDecl[] | null;
export type Name1 = string;
export type Description1 = string | null;
export type Inputschema = {
  [k: string]: unknown;
} | null;
export type Subagents = SubagentDecl[] | null;
export type Name2 = string;
export type Description2 = string | null;
export type Inputschema1 = {
  [k: string]: unknown;
} | null;
export type AvpAgentType = string | null;
export type Skills = SkillDecl[] | null;
export type Name3 = string;
export type Description3 = string | null;
export type Version = string | null;
export type AvpSource = string | null;
export type Capabilities = string[] | null;

/**
 * The agent's self-description. Enumerates built-in tools, subagents, and skills triggerable without supervisor configuration, plus the agent's identity, capabilities, and supported models. Pre-flight (`<agent> describe` stdout) and run-time (`agent_described.data['avp.descriptor']`) views MUST match for the same agent build. See spec/v0.1/agent-descriptor.md.
 */
export interface AVPV01AgentDescriptor {
  agent_name: AgentName;
  agent_version: AgentVersion;
  spec_version: SpecVersion;
  default_model?: DefaultModel;
  supported_models?: SupportedModels;
  system_prompt?: SystemPrompt;
  prompt?: Prompt;
  mcp_servers?: McpServers;
  tools?: Tools;
  subagents?: Subagents;
  skills?: Skills;
  capabilities?: Capabilities;
}
/**
 * MCP server descriptor in `AgentDescriptor.mcp_servers`: identity only.
 *
 * Connection material (URLs, auth, command-lines) stays inside the agent
 * process and is NOT carried on the descriptor wire. The descriptor
 * records only the server's id, optional display name, and optional
 * description; the tools the server surfaces are NOT enumerated on the
 * descriptor — they appear at runtime on
 * `mcp_server_connected.data["avp.mcp.tools"]`.
 *
 * `id` is the agent's correlation key for this server across the wire
 * (descriptor entry, `mcp_server_connected` event, tool dispatch). It
 * is intentionally looser than `Commission.McpServerRef.id`: the
 * descriptor enumerates BOTH Commission-resolved servers (where `id` is
 * the supervisor-authored slug) AND agent-baked-in / environment-resident
 * servers (where `id` is whatever the environment names them, e.g.
 * `"claude.ai Dashboard Builder"`). Forcing a slug here would either
 * lose fidelity or require every agent to invent the same slugification
 * rule. Commission-authored ids stay slug-clean by virtue of
 * `Commission.McpServerRef.id`'s pattern; descriptor ids must only be
 * non-empty and must match the `avp.mcp.server_id` the agent later
 * surfaces on `mcp_server_connected` so consumers can correlate.
 *
 * `name` is the display name when the environment provides one distinct
 * from `id` (typical for Commission-resolved servers: `id` is the
 * Commission slug, `name` is the human-readable label from the resolved
 * config). For environment-resident servers whose only identifier is
 * the display name, `id` carries that string and `name` is omitted.
 *
 * This interface was referenced by `AVPV01AgentDescriptor`'s JSON-Schema
 * via the `definition` "McpServerDecl".
 */
export interface McpServerDecl {
  id: Id;
  name?: Name;
  description?: Description;
  [k: string]: unknown;
}
/**
 * Tool descriptor used by `AgentDescriptor.tools`,
 * `agent_started.data["avp.tools"]`, and `mcp_server_connected.data.avp.mcp.tools`.
 *
 * MCP-shaped: `name` plus optional `description` and `inputSchema`. The
 * decl describes a single tool's model-facing identity; how the tool is
 * *dispatched* (local vs MCP server) is implicit from where the decl
 * appears on the wire — `descriptor.tools` and `agent_started.data["avp.tools"]`
 * are local-only; entries under `mcp_server_connected.data.avp.mcp.tools`
 * are MCP-dispatched by virtue of being nested under a server. The
 * per-invocation discriminator lives on `tool_invoked.data["avp.tool.dispatch_target"]`.
 *
 * This interface was referenced by `AVPV01AgentDescriptor`'s JSON-Schema
 * via the `definition` "ToolDecl".
 */
export interface ToolDecl {
  name: Name1;
  description?: Description1;
  inputSchema?: Inputschema;
  [k: string]: unknown;
}
/**
 * Subagent descriptor in `agent_started.data["avp.subagents"]`: what the
 * parent model sees when deciding whether to delegate. Same MCP-shaped
 * triple (`name`, `description`, `inputSchema`) tools use, so adapters
 * can render subagents to the model's tool list with no translation.
 *
 * `description` is optional to match `ToolDecl`: when surfacing a
 * agent-built-in subagent (e.g. the Claude Agent SDK's `general-purpose`)
 * the agent has authoritative knowledge of the name but not the prose
 * description. Honest-null beats authored-prose-that-drifts.
 *
 * This interface was referenced by `AVPV01AgentDescriptor`'s JSON-Schema
 * via the `definition` "SubagentDecl".
 */
export interface SubagentDecl {
  name: Name2;
  description?: Description2;
  inputSchema?: Inputschema1;
  "avp.agent_type"?: AvpAgentType;
  [k: string]: unknown;
}
/**
 * Skill descriptor in `AgentDescriptor.skills` and
 * `agent_started.data["avp.skills"]`: name plus optional metadata about each
 * skill the agent ships with or has loaded for the run.
 *
 * Replaces the v0.1-prototype `list[str]` shape (names-only) with a
 * structured decl matching `ToolDecl` / `SubagentDecl`. Description
 * comes from the SKILL.md frontmatter when the agent surfaces it
 * (e.g. via `ClaudeSDKClient.get_context_usage()` which returns a
 * `skills` breakdown including frontmatter); `version` is the skill's
 * own version when known; `avp.source` is the SKILL.md path / URI.
 *
 * All fields except `name` are optional so agents that only know
 * the name (Commission-declared without enrichment) still emit valid
 * decls.
 *
 * This interface was referenced by `AVPV01AgentDescriptor`'s JSON-Schema
 * via the `definition` "SkillDecl".
 */
export interface SkillDecl {
  name: Name3;
  description?: Description3;
  version?: Version;
  "avp.source"?: AvpSource;
  [k: string]: unknown;
}
