/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type SchemaVersion = "0.1";
export type RunId = string;
export type Name = string;
export type Version = string | null;
export type McpServers = McpServer[] | null;
export type Id = string;
export type Transport = "http" | "stdio";
export type Url = string | null;
export type Type = "bearer";
export type TokenEnv = string;
export type Command = string[] | null;
export type Args = string[] | null;
export type Env = {
  [k: string]: string;
} | null;
export type InitTimeoutMs = number;
export type Meta = {
  [k: string]: unknown;
} | null;
export type OutputSchema = {
  [k: string]: unknown;
} | null;
export type Subagents = Subagent[] | null;
export type Name1 = string;
export type Description = string;
export type Inputschema = {
  [k: string]: unknown;
} | null;
export type SystemPrompt = string | null;
export type Model = string | null;
export type InheritTools = boolean;
export type Exposed = string[];
export type McpServers1 = McpServer[] | null;
export type Skills = Skill[] | null;
export type Name2 = string;
export type AvpSource = string;
export type AvpConfig = {
  [k: string]: unknown;
} | null;
export type OutputSchema1 = {
  [k: string]: unknown;
} | null;
export type Subagents1 = Subagent[] | null;
export type Exposed1 = string[];
export type Prompt = string | null;
export type SystemPrompt1 = string | null;
export type Model1 = string | null;
export type Skills1 = Skill[] | null;
export type ThreadId = string | null;
export type Tags = string[] | null;
export type Meta1 = {
  [k: string]: unknown;
} | null;

/**
 * Supervisor → agent setup message. Declares the agent's complete environment (mcp_servers, allowed_tools, skills, subagents, prompts). Sent once at startup. The supervisor MUST NOT modify the environment mid-run.
 */
export interface AVPV01Commission {
  schema_version: SchemaVersion;
  run_id: RunId;
  supervisor?: SupervisorPreamble | null;
  mcp_servers?: McpServers;
  output_schema?: OutputSchema;
  subagents?: Subagents;
  exposed: Exposed1;
  prompt?: Prompt;
  system_prompt?: SystemPrompt1;
  model?: Model1;
  skills?: Skills1;
  thread_id?: ThreadId;
  tags?: Tags;
  meta?: Meta1;
}
/**
 * Identifies the supervisor that is requesting the run.
 *
 * Carried inside `Commission.supervisor` and stamped onto the
 * `run_requested` event the agent emits as the first event of the
 * trajectory (with `source: avp://supervisor`). Lets a trajectory
 * consumer attribute the run to the originating supervisor without an
 * out-of-band lookup.
 *
 * `name` SHOULD be a stable identifier for the supervisor implementation
 * or instance (e.g. `"simple-supervisor-example"`, `"acme.scheduler"`).
 * `version` is optional but recommended — it travels with the trajectory
 * and lets auditors correlate a run with the exact supervisor build
 * that requested it.
 *
 * This interface was referenced by `AVPV01Commission`'s JSON-Schema
 * via the `definition` "SupervisorPreamble".
 */
export interface SupervisorPreamble {
  name: Name;
  version?: Version;
}
/**
 * External MCP server endpoint. The agent connects, runs initialize +
 * tools/list, and merges returned tools into the effective surface.
 *
 * This interface was referenced by `AVPV01Commission`'s JSON-Schema
 * via the `definition` "McpServer".
 */
export interface McpServer {
  id: Id;
  transport: Transport;
  url?: Url;
  auth?: McpHttpAuth | null;
  command?: Command;
  args?: Args;
  env?: Env;
  init_timeout_ms?: InitTimeoutMs;
  _meta?: Meta;
}
/**
 * Auth for an MCP server reachable via HTTP.
 *
 * This interface was referenced by `AVPV01Commission`'s JSON-Schema
 * via the `definition` "McpHttpAuth".
 */
export interface McpHttpAuth {
  type?: Type;
  token_env: TokenEnv;
}
/**
 * Declares a sub-agent the parent can delegate to.
 *
 * Sits alongside `tools` and `skills` as a top-level Commission primitive: the
 * supervisor declares the full set of subagents up front, the parent agent
 * invokes one by name at runtime. The model surface is MCP-shaped (`name`,
 * `description`, `inputSchema`) so the model sees a subagent the same way
 * it sees a tool. The wire surface is its own lifecycle —
 * `subagent_invoked` / `subagent_returned` / `subagent_failed` — so
 * nested turns and tool calls observe as their own span tree rather than
 * flatten into a single tool call.
 *
 * A Subagent carries an environment slice that mirrors Commission (its own
 * `system_prompt`, `model`, `tools`, `skills`, `output_schema`). The subagent runs in a fresh conversation —
 * `inherit_tools=False` by default (matches Google ADK; safer than the
 * Claude Agent SDK default of inheriting). Skills and prompt context are
 * never inherited.
 *
 * This interface was referenced by `AVPV01Commission`'s JSON-Schema
 * via the `definition` "Subagent".
 */
export interface Subagent {
  name: Name1;
  description: Description;
  inputSchema?: Inputschema;
  system_prompt?: SystemPrompt;
  model?: Model;
  inherit_tools?: InheritTools;
  exposed?: Exposed;
  mcp_servers?: McpServers1;
  skills?: Skills;
  output_schema?: OutputSchema1;
  subagents?: Subagents1;
}
/**
 * Reference to a SKILL.md following the agentskills.io specification.
 *
 * `name` MUST follow agentskills.io rules (1-64 chars, lowercase a-z digits
 * hyphens, no leading/trailing hyphen, no consecutive hyphens). The
 * `avp_source` and `avp_config` fields are AVP extensions; agentskills.io
 * doesn't define a remote-load scheme.
 *
 * This interface was referenced by `AVPV01Commission`'s JSON-Schema
 * via the `definition` "Skill".
 */
export interface Skill {
  name: Name2;
  "avp.source": AvpSource;
  "avp.config"?: AvpConfig;
}
