/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type SchemaVersion = "0.1";
export type RunId = string;
export type Name = string;
export type Version = string | null;
export type McpServers = McpServerRef[] | null;
export type Id = string;
/**
 * This interface was referenced by `AVPV01Commission`'s JSON-Schema
 * via the `definition` "JsonValue".
 */
export type JsonValue = unknown;
export type Skills = SkillRef[] | null;
export type Id1 = string;
export type Subagents = SubagentRef[] | null;
export type Id2 = string;
export type EnabledBuiltinTools = string[] | null;
export type EnabledBuiltinSubagents = string[] | null;
export type EnabledBuiltinSkills = string[] | null;
export type EnabledBuiltinMcpServers = string[] | null;
export type OutputSchema = {
  [k: string]: unknown;
} | null;
export type Prompt = string | null;
export type SystemPrompt = string | null;
export type Model = string | null;
export type ThreadId = string | null;
export type Tags = string[] | null;
export type Meta = {
  [k: string]: unknown;
} | null;

/**
 * Supervisor → agent setup message. Declares prompt, model, and supervisor-managed assets (mcp_servers, skills, subagents) as opaque {id, ref} pairs the agent dereferences via the AVP Resolver API at startup. Sent once at startup. See spec/v0.1/commission.md.
 */
export interface AVPV01Commission {
  schema_version: SchemaVersion;
  run_id: RunId;
  supervisor?: SupervisorPreamble | null;
  mcp_servers?: McpServers;
  skills?: Skills;
  subagents?: Subagents;
  enabled_builtin_tools?: EnabledBuiltinTools;
  enabled_builtin_subagents?: EnabledBuiltinSubagents;
  enabled_builtin_skills?: EnabledBuiltinSkills;
  enabled_builtin_mcp_servers?: EnabledBuiltinMcpServers;
  output_schema?: OutputSchema;
  prompt?: Prompt;
  system_prompt?: SystemPrompt;
  model?: Model;
  thread_id?: ThreadId;
  tags?: Tags;
  meta?: Meta;
}
/**
 * Identifies the supervisor that is requesting the run.
 *
 * Carried inside `Commission.supervisor` and projected onto the
 * `run_requested` event's `data` (`avp.supervisor.name` +
 * `avp.supervisor.version`) so a trajectory consumer can attribute the
 * run to the originating supervisor without an out-of-band lookup. The
 * event's `source` is `avp://agent` (the agent is the sole producer on
 * the wire); supervisor attribution lives inside `data`.
 *
 * `name` SHOULD be a stable identifier for the supervisor implementation
 * or instance (e.g. `"simple-supervisor-example"`, `"acme.scheduler"`).
 * `version` is optional but recommended; it travels with the trajectory
 * and lets auditors correlate a run with the exact supervisor build
 * that requested it.
 *
 * This interface was referenced by `AVPV01Commission`'s JSON-Schema
 * via the `definition` "SupervisorPreamble".
 */
export interface SupervisorPreamble {
  name: Name;
  version?: Version;
}
/**
 * Reference to a supervisor-managed MCP server.
 *
 * The agent resolves this entry at startup by calling `avp.resolve` with
 * `{kind: "mcp_server", id, ref}`. The resolver returns the connection
 * material (transport, URL, auth, etc.) the agent uses to dial the actual
 * MCP server. Per-`kind` result schemas are pinned in the Resolver API
 * spec (`spec/v0.1/resolver.md` §3.2). Auth and transport are deployment
 * concerns; AVP does not constrain them.
 *
 * This interface was referenced by `AVPV01Commission`'s JSON-Schema
 * via the `definition` "McpServerRef".
 */
export interface McpServerRef {
  id: Id;
  ref: JsonValue;
}
/**
 * Reference to a supervisor-managed skill.
 *
 * The agent resolves this entry at startup by calling `avp.resolve` with
 * `{kind: "skill", id, ref}`. The resolver returns the SKILL.md content
 * (or a location the agent fetches and reads); agentskills.io's content
 * model still applies; the resolver just hands the content back from
 * whatever store the supervisor uses.
 *
 * This interface was referenced by `AVPV01Commission`'s JSON-Schema
 * via the `definition` "SkillRef".
 */
export interface SkillRef {
  id: Id1;
  ref: JsonValue;
}
/**
 * Reference to a supervisor-managed subagent.
 *
 * The agent resolves this entry at startup by calling `avp.resolve` with
 * `{kind: "subagent", id, ref}`; the resolver returns the model-facing
 * metadata (`name`, `description`, `inputSchema`) so the parent's model
 * can decide whether to delegate. When the model invokes the subagent at
 * runtime, the agent calls `avp.spawn_subagent` with the same ref to
 * obtain a child `run_id`. The subagent run carries its own complete
 * trajectory; the parent's `subagent_invoked.data["avp.subagent.run_id"]`
 * references it.
 *
 * This interface was referenced by `AVPV01Commission`'s JSON-Schema
 * via the `definition` "SubagentRef".
 */
export interface SubagentRef {
  id: Id2;
  ref: JsonValue;
}
