"""Track recent eval runs so `avp eval view` / `list` can find them — even when
a run wrote to a `--out` directory.

A small JSONL history under the run-outputs root (`~/.avp/runs`, see `paths`).
Each `avp eval run` appends one record; readers return runs newest-first, deduped
by output directory, and filtered to those whose `trajectories*.json` still exist
on disk. `avp eval delete <id>` removes one run; `avp eval delete --all` wipes them all.
"""

from __future__ import annotations

import json
import re
import secrets
import shutil
from datetime import UTC, datetime
from pathlib import Path
from typing import Any

from avp_cli import paths

# Voyage names: each eval run is a voyage, so its handle is a short, memorable
# two-word slug (e.g. "swift-harbor") rather than a temp-dir path. This is the id
# `avp eval run` prints, `avp eval list` shows, and `avp eval view <id>` opens.
_ADJ = (
    "calm", "swift", "bold", "brisk", "clear", "fair", "steady", "bright",
    "deep", "lone", "north", "south", "salt", "tidal", "open", "still",
    "wild", "far", "grey", "blue",
)  # fmt: skip
_NOUN = (
    "harbor", "tide", "current", "reef", "wake", "bay", "cove", "channel",
    "horizon", "compass", "anchor", "mast", "keel", "helm", "port", "shoal",
    "gale", "swell", "drift", "beacon",
)  # fmt: skip


def _home() -> Path:
    return paths.runs_dir()


def _history_path(home: Path) -> Path:
    return home / "history.jsonl"


def _taken_ids(home: Path) -> set[str]:
    return {r["id"] for r in recent_runs(limit=10_000, home=home) if r.get("id")}


def _is_free(cand: str, taken: set[str], home: Path) -> bool:
    return cand not in taken and not (home / cand).exists()


def new_id(*, home: Path | None = None) -> str:
    """A short, memorable voyage handle for one eval run (e.g. 'swift-harbor').

    Unique against the ids already in history and any existing run dir under the
    default home, so `avp eval view <id>` resolves to exactly one run.
    """
    home = home or _home()
    taken = _taken_ids(home)
    for _ in range(64):
        cand = f"{secrets.choice(_ADJ)}-{secrets.choice(_NOUN)}"
        if _is_free(cand, taken, home):
            return cand
    return f"{secrets.choice(_ADJ)}-{secrets.choice(_NOUN)}-{secrets.token_hex(2)}"


def slugify(name: str) -> str:
    """Make a user-typed run name into a filesystem/url-safe id ('My Run' -> 'my-run')."""
    return re.sub(r"[^a-z0-9]+", "-", name.strip().lower()).strip("-")


def claim_id(name: str, *, home: Path | None = None) -> str:
    """Turn a chosen run name into a unique voyage id.

    Slugifies it and, if that id is already taken, suffixes `-2`, `-3`, ... so a
    named run never clobbers an earlier one. A name that slugs to nothing falls
    back to an autogenerated id.
    """
    home = home or _home()
    base = slugify(name)
    if not base:
        return new_id(home=home)
    taken = _taken_ids(home)
    cand, i = base, 2
    while not _is_free(cand, taken, home):
        cand, i = f"{base}-{i}", i + 1
    return cand


def record_run(
    *,
    run_id: str,
    out_dir: str | Path,
    dataset: str,
    agents: list[str],
    commissions: list[str],
    home: Path | None = None,
) -> None:
    """Append one run record to the history log."""
    home = home or _home()
    home.mkdir(parents=True, exist_ok=True)
    rec = {
        "id": run_id,
        "ts": datetime.now(UTC).isoformat(),
        "out_dir": str(Path(out_dir).resolve()),
        "dataset": dataset,
        "agents": list(agents),
        "commissions": list(commissions),
    }
    with _history_path(home).open("a") as f:
        f.write(json.dumps(rec) + "\n")


def _has_trajectories(d: Path) -> bool:
    return d.is_dir() and any(d.glob("trajectories*.json"))


def recent_runs(limit: int = 20, *, home: Path | None = None) -> list[dict[str, Any]]:
    """Run records, newest first, deduped by out_dir, only those still on disk."""
    path = _history_path(home or _home())
    if not path.is_file():
        return []
    records: list[dict[str, Any]] = []
    for line in path.read_text().splitlines():
        line = line.strip()
        if not line:
            continue
        try:
            records.append(json.loads(line))
        except json.JSONDecodeError:
            continue
    seen: set[str] = set()
    out: list[dict[str, Any]] = []
    for rec in reversed(records):
        d = rec.get("out_dir")
        if not d or d in seen:
            continue
        seen.add(d)
        if _has_trajectories(Path(d)):
            out.append(rec)
        if len(out) >= limit:
            break
    return out


def last_run(*, home: Path | None = None) -> dict[str, Any] | None:
    runs = recent_runs(limit=1, home=home)
    return runs[0] if runs else None


def find_run(run_id: str, *, home: Path | None = None) -> dict[str, Any] | None:
    """The most recent live run with this voyage id (or None)."""
    for r in recent_runs(limit=10_000, home=home):
        if r.get("id") == run_id:
            return r
    return None


def clear_runs(*, home: Path | None = None) -> int:
    """Delete all recorded runs + their output dirs. Returns how many were cleared."""
    home = home or _home()
    n = len(recent_runs(limit=10_000, home=home))
    shutil.rmtree(home, ignore_errors=True)
    return n


def delete_run(run_id: str, *, home: Path | None = None) -> bool:
    """Delete one recorded run by id: its output dir(s) + every history entry for it.

    Returns True if anything was deleted, False if no record had that id. Removes
    all history records sharing the run's id or output dir (re-runs into the same
    dir appended multiple), then rewrites the log without them.
    """
    home = home or _home()
    path = _history_path(home)
    if not path.is_file():
        return False
    records: list[dict[str, Any]] = []
    for line in path.read_text().splitlines():
        line = line.strip()
        if not line:
            continue
        try:
            records.append(json.loads(line))
        except json.JSONDecodeError:
            continue
    out_dirs = {r.get("out_dir") for r in records if r.get("id") == run_id and r.get("out_dir")}
    if not out_dirs:
        return False
    for d in out_dirs:
        shutil.rmtree(d, ignore_errors=True)
    kept = [r for r in records if r.get("id") != run_id and r.get("out_dir") not in out_dirs]
    path.write_text("".join(json.dumps(r) + "\n" for r in kept))
    return True
