/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type SystemPrompt = string | null;
export type Prompt = string | null;
export type Name = string;
export type Description = string | null;
export type InputSchema = {
  [k: string]: unknown;
} | null;
export type McpServerId = string | null;
export type Tools = BuiltinTool[];
export type Name1 = string;
export type Description1 = string | null;
export type Version = string | null;
export type Source = string | null;
export type Skills = BuiltinSkill[];
export type Id = string;
export type Name2 = string | null;
export type Description2 = string | null;
export type McpServers = BuiltinMcpServer[];
export type Name3 = string;
export type Description3 = string | null;
export type InputSchema1 = {
  [k: string]: unknown;
} | null;
export type AgentType = string | null;
export type Subagents = BuiltinSubagent[];

/**
 * Test fixture consumed by an SDK's conformance entrypoint via `--built-in <json|path>`. The SDK MUST behave as if these are its actual built-ins for the run (system_prompt, tools, skills, mcp_servers, subagents), then apply Commission overrides per the AVP merge spec. Not part of the wire format; only used by the conformance harness.
 */
export interface AgentBuiltins {
  system_prompt?: SystemPrompt;
  prompt?: Prompt;
  tools?: Tools;
  skills?: Skills;
  mcp_servers?: McpServers;
  subagents?: Subagents;
}
/**
 * One tool the case pretends the SDK has built-in.
 *
 * This interface was referenced by `AgentBuiltins`'s JSON-Schema
 * via the `definition` "BuiltinTool".
 */
export interface BuiltinTool {
  name: Name;
  description?: Description;
  input_schema?: InputSchema;
  mcp_server_id?: McpServerId;
}
/**
 * One skill the case pretends the SDK has built-in.
 *
 * This interface was referenced by `AgentBuiltins`'s JSON-Schema
 * via the `definition` "BuiltinSkill".
 */
export interface BuiltinSkill {
  name: Name1;
  description?: Description1;
  version?: Version;
  source?: Source;
}
/**
 * One MCP server the case pretends the SDK has built-in.
 *
 * Connection material (URL, auth, command line) is irrelevant for the
 * fixture; only identity surfaces, since merge logic operates on `id`.
 *
 * This interface was referenced by `AgentBuiltins`'s JSON-Schema
 * via the `definition` "BuiltinMcpServer".
 */
export interface BuiltinMcpServer {
  id: Id;
  name?: Name2;
  description?: Description2;
}
/**
 * One subagent the case pretends the SDK has built-in.
 *
 * This interface was referenced by `AgentBuiltins`'s JSON-Schema
 * via the `definition` "BuiltinSubagent".
 */
export interface BuiltinSubagent {
  name: Name3;
  description?: Description3;
  input_schema?: InputSchema1;
  agent_type?: AgentType;
}
